
INSERT INTO `RIGHT_GROUP` VALUES ('35', '华侨城', 'admin', '2013-11-28 00:45:53', '', '1', '5');
INSERT INTO `RIGHT_ROLE` VALUES ('100', '运营商角色', 'admin', '2013-10-18 14:51:54', '运营商角色', '0','35','0');
INSERT INTO `RIGHT_GROUP_ROLE` VALUES ('2', '35', '100');
INSERT INTO `COMMON_MEMBER` VALUES ('2', 'operator', 'ww@ee.com', '11', 'C4CA4238A0B923820DCC509A6F75849B', '0', '0', '0:0:0:0:0:0:0:1', '2013-09-25 19:19:38', '0', null, '0', '0', '0', null, '0', '0', '35', '100');

INSERT INTO `COMMON_MEMBER` VALUES ('1', 'admin', 'admin@oct.com', '34', 'C4CA4238A0B923820DCC509A6F75849B', '0', '0', '127.0.0.1', '2013-09-25 19:19:38', '0', null, '0', '0', '0', null, '0', '0', '5', '120');

INSERT INTO `RIGHT_GROUP` VALUES ('5', '系统核心', 'admin', '2013-11-15 09:36:11', '系统核心', '125', '0');

INSERT INTO `SYS_CONFIG` VALUES ('NO_RIGHT_PATHS', '/system/login.json,/system/index.html,/pay/inputParams.html,/pay/generateMainPage.html,/pay/forwordChannel.html,/pay/componentRequest.html,/pay/componentParse4Web.html,/pay/componentParse4Wap.html,/system/index.html,/console/login.json,/system/center.html,/menuItem/showMenu.json,/system/loginOut.html,/report/base/data/findAllDepartment.json,/report/base/data/findScenicByDepartmentId.json,/verifyVoucher,/register/signIn,/register/signOut,/member/findGroup.json,/member/findRoleByGroupId.json,/dictionary/read.json,/api/send/getSightInfo,/api/send/getTicketInfo,/api/send/queryOrderList,/api/send/resendVoucher,/api/send/checkTicket,/api/send/confirmOrder,/api/send/refund,/goodsCommon/updateFinanceCheckStatus.json,/goodsCommon/updateStatus.json,/goodsCommon/updateCheckStatus.json,/goodsCommon/saveGoodsCommon.json,/goodsCommon/updateGoodsCommon.json,/goodsCommon/delGoods.json,voucher/checkOnLine.json,operation/system/getSystemCodeByType.json,/operation/system/initCodeMould.json', '不需要权限过滤', '非过滤请求地址以\',\'号分隔', '2013-10-18 14:45:19');

INSERT INTO `RIGHT_ROLE` VALUES ('120', '超级管理员', 'admin', '2013-11-27 07:16:14', '超级管理员', '0', '5', '0');
INSERT INTO `RIGHT_ROLE` VALUES ('125', '顶级机构', 'admin', '2013-11-27 21:21:53', '顶级机构', '0', null, '1');
INSERT INTO `RIGHT_ROLE` VALUES ('1', '运营商', 'admin', '2013-11-28 00:45:17', '运营商', '125', null, '1');
INSERT INTO `RIGHT_ROLE` VALUES ('2', '事业部', 'admin', '2013-11-28 01:17:28', '事业部类型', '1', null, '1');
INSERT INTO `RIGHT_ROLE` VALUES ('3', '景区', 'admin', '2013-11-28 01:18:05', '景区类型', '1', null, '1');
INSERT INTO `RIGHT_ROLE` VALUES ('6', '渠道商', 'admin', '2013-11-28 01:24:40', '渠道商类型', '3', null, '1');

INSERT INTO `RIGHT_MENUITEM` VALUES ('1', '根菜单', null, '1', '1', '2013-09-22 15:23:53', '1', null, '0', '1', null, null, null, null);
INSERT INTO `RIGHT_MENUITEM` VALUES ('21', '系统核心组', '框架', 'qwewq', 'admin', '2013-10-28 11:30:43', 'demo-shortcut', 'icon-grid', '22', '1', '0', '0', null, '1');
INSERT INTO `RIGHT_MENUITEM` VALUES ('25', '分组管理', 'groupview', 'framework.GroupController', 'admin', '2013-11-27 01:36:51', 'groupBig', 'groupSmall', '20', '1', '1', '1', '', '21');
INSERT INTO `RIGHT_MENUITEM` VALUES ('2', '操作管理', 'operateview', 'framework.OperateController', 'user+i', '2013-09-24 09:09:59', 'actionBig', 'actionSmall', '2', '1', '0', '1', '/operate/findOperate.json', '21');
INSERT INTO `RIGHT_MENUITEM` VALUES ('3', '分组管理', 'groupPanel', 'groupPanel', 'user3', '2013-09-23 14:30:09', 'crm-fenzu', 'icon-grid', '55', '1', '1', '1', '/group/query.json', '25');
INSERT INTO `RIGHT_MENUITEM` VALUES ('4', '角色管理', 'roleview', 'framework.RoleController', 'user5', '2013-09-23 14:30:09', 'roleBig', 'roleSmall', '12', '1', '1', '1', '/role/findRole.json', '21');
INSERT INTO `RIGHT_MENUITEM` VALUES ('5', '菜单管理', 'menuitemview', 'framework.MenuItemController', 'user6', '2013-09-23 14:30:09', 'menuBig', 'menuSmall', '100', '1', '1', '1', '/menuItem/findMenuItemList.json', '21');
INSERT INTO `RIGHT_MENUITEM` VALUES ('6', '管理员管理', 'userview', 'framework.UserController', 'user', '2013-10-21 11:55:09', 'userBig', 'userSmall', '10', '1', '1', '1', 'member/findUser.json,member/delete.json,member/update.json,member/save.json,member/findRoleByGroupId.json,member/findGroup.json', '21');
INSERT INTO `RIGHT_MENUITEM` VALUES ('24', '业务管理', 'businessView1', 'BusinessController', 'admin', '2013-11-15 15:07:53', 'crm-xtpz', 'a', '43', '0', '1', '1', '', '21');
INSERT INTO `RIGHT_MENUITEM` VALUES ('26', '机构类型', '机构类型', 'groupTypePanel', 'admin', '2013-11-27 02:01:06', '', '', '100', '1', '1', '1', '', '25');

INSERT INTO `RIGHT_MENUITEM` VALUES ('11', '任务管理', 'taskview', 'framework.TaskController', 'admin', '2013-11-27 02:01:06', '', '', '100', '1', '1', '1', '', '21');
INSERT INTO `RIGHT_MENUITEM` VALUES ('12', '任务列表', 'taskPanel', 'taskPanel', 'admin', '2013-11-27 02:01:06', '', '', '100', '1', '1', '1', '', '11');
INSERT INTO `RIGHT_MENUITEM` VALUES ('13', '任务日志', 'taskLogPanel', 'taskLogPanel', 'admin', '2013-11-27 02:01:06', '', '', '100', '1', '1', '1', '', '11');

INSERT INTO `RIGHT_MENUITEM` VALUES ('7', '运营商后台菜单', null, 'test', 'admin', '2013-11-12 11:53:40', '1', null, '1', '1', '0', '0', 'test', '1');
INSERT INTO `RIGHT_MENUITEM` VALUES ('8', '事业部后台菜单', null, 'test', 'admin', '2013-11-12 11:53:40', '1', null, '1', '1', '0', '0', 'test', '1');
INSERT INTO `RIGHT_MENUITEM` VALUES ('9', '景区后台菜单', null, 'test', 'admin', '2013-11-12 11:53:40', '1', null, '1', '1', '0', '0', 'test', '1');
INSERT INTO `RIGHT_MENUITEM` VALUES ('10', '渠道商后台菜单', null, 'test', 'admin', '2013-11-12 11:53:40', '1', null, '1', '1', '0', '0', 'test', '1');
INSERT INTO `RIGHT_MENUITEM` VALUES ('43', '通用商品管理', 'goodscommonview', 'scenic.GoodsCommonController', 'admin', '2013-10-23 16:13:29', 'goodsBig', 'goodsSmall', '1', '1', '1', '1', '/goodsCommon/getGoodsUseValidityList.json,/goodsCommon/getMyRelateGoodsList.json,/goodsCommon/getSmsModelList.json,/goodsCommon/getTicketModelList.json,/goodsCategory/getGoodsCategoryListByTypeCode.json,/goodsCommon/editGoodsCommon.json,/goodsCategory/getGoodsCategoryListByPage.json,/goodsCategory/addGoodsCategory.json,/goodsCategory/updateGoodsCategory.json,/goodsCategory/deleteGoodsCategory.json/goodsCommon/findGoodsCommonList.json,/goodsCommon/saveScenicTicket.json,/goodsCommon/updateScenicTicket.json,/goodsCommon/delnGoods.json,/goodsCategory/findGoodsCategoryList.json,/goodsCategory/findGoodsCategoryList2.json,/goodsCategory/getGoodsCategornyListByParentId.json,/goodsCommon/getSupplierListByPage.json,/goodsCommon/getConsumeAreaList.json,/goodsCommon/getMerchantListnByPage.json,/goodsCommon/getRelateGoodsList.json,/goodsType/getAllGoodsTypeList.json,/goodsSchedule/getGoodsScheduleLisForCom.json,/goodsCategory/getGoodsCategoryListByLevel1.json', '9');
INSERT INTO `RIGHT_MENUITEM` VALUES ('44', '机构管理', 'instview', 'operation.inst.InstController', 'admin', '2013-10-23 16:15:25', 'organizationBig', 'organizationBigSmall', '1', '1', '1', '1', '/inst/add.json,/inst/distribute.json,/inst/remove.json,/inst/update.json,/inst/add.json,/inst/approve.json,/inst/list.json,/area/levelList.json', '7');
INSERT INTO `RIGHT_MENUITEM` VALUES ('49', '景区门票管理', 'scenicticketview', 'scenic.ScenicTicketController', 'admin', '2013-10-23 16:47:54', 'ticketBig', 'ticketSmall', '1', '1', '1', '1', '/goodsCommon/findGoodsCommonList.json,/goodsCommon/saveScenicTicket.json,/goodsCommon/updateScenicTicket.json,/goodsCommon/delnGoods.json,/goodsCategory/findGoodsCategoryList.json,/goodsCategory/findGoodsCategoryList2.json,/goodsCategory/getGoodsCategornyListByParentId.json,/goodsCommon/getSupplierListByPage.json,/goodsCommon/getConsumeAreaList.json,/goodsCommon/getMerchantListnByPage.json,/goodsCommon/getRelateGoodsList.json,/goodsType/getAllGoodsTypeList.json,/goodsSchedule/getGoodsScheduleLisForCom.njson,/goodsCommon/getGoodsUseValidityList.json,/goodsCommon/getMyRelateGoodsList.json,/goodsCommon/getSmsModelList.json,/goodsCommon/getTicketModelList.json,/goodsCategory/getGoodsCategoryListByTypeCode.json,/goodsCommon/editGoodsCommon.json,/goodsCategory/getGoodsCategoryListByPage.json,/goodsCategory/addGoodsCategory.json,/goodsCategory/updateGoodsCategory.json,/goodsCategory/deleteGoodsCategory.json', '9');
INSERT INTO `RIGHT_MENUITEM` VALUES ('56', '商品类型管理', 'goodstypeview', 'scenic.GoodsTypeController', 'admin', '2013-10-23 17:09:26', 'goodsTypeBig', 'goodsTypeSmall', '1', '1', '1', '1', '/goodsType/getGoodsTypeListByPage.json,/goodsType/saveGoodsType.json,/goodsType/updateGoodsType.json,/goodsType/deleteGoodsType.json,/scenicSpot/listReloateGoodsType.json', '7');
INSERT INTO `RIGHT_MENUITEM` VALUES ('61', '导游管理', 'tourguideview', 'operation.tourguide.TourGuideController', 'admin', '2013-10-23 17:18:32', 'guideBig', 'guideSmall', '1', '1', '1', '1', '/tourGuide/findTourGuide.json,/tourGuide/insertTourGuide.json,/tourGuide/updateTourGuide.json,/tourGuide/findTourGuide.json?isBlacklist=1', '7');
INSERT INTO `RIGHT_MENUITEM` VALUES ('62', '报表中心', 'reportmainview', 'report.ReportMainController', 'admin', '2013-10-23 17:49:21', 'reportBig', 'reportSmall', '10', '1', '1', '1', '/report/org/findSaleReportPieChartData.json', '1');
INSERT INTO `RIGHT_MENUITEM` VALUES ('63', '渠道商管理', 'channelview', 'scenic.channel.ChannelController', 'admin', '2013-10-23 18:08:03', 'channelBig', 'channelSmall', '0', '1', '1', '1', null, '9');
INSERT INTO `RIGHT_MENUITEM` VALUES ('64', '网站维护', 'sitemgrview', 'scenic.sitemgr.SiteMgrController', 'admin', '2013-10-24 09:45:28', 'webBig', 'webSmall', '1', '1', '1', '1', null, '7');
INSERT INTO `RIGHT_MENUITEM` VALUES ('65', '订单管理', 'scenicview', 'scenic.order.OrderController', 'admin', '2013-10-24 09:53:09', 'orderBig', 'orderSmall', '1', '1', '1', '1', null, '9'); 
INSERT INTO `RIGHT_MENUITEM` VALUES ('68', '规则管理', 'settlemgrview', 'operation.settlemgr.SettleMgrController', 'admin', '2013-10-24 14:34:04', 'ruleBig', 'ruleSmall', '1', '1', '1', '1', null, '9');
INSERT INTO `RIGHT_MENUITEM` VALUES ('69', '事业部管理', 'businessview', 'operation.business.BusinessController', 'admin', '2013-10-24 14:49:05', 'divisionBig', 'divisionSmall', '1', '1', '1', '1', null, '7');
INSERT INTO `RIGHT_MENUITEM` VALUES ('72', '供应商管理', 'supplierview', 'operation.supplier.SupplierController', 'admin', '2013-10-24 19:35:25', 'supplierBig', 'supplierSmall', '1', '1', '1', '1', null, '7');
INSERT INTO `RIGHT_MENUITEM` VALUES ('73', '商户管理', 'merchantview', 'operation.merchant.MerchantController', 'admin', '2013-10-24 21:27:20', 'merchantBig', 'merchantSmall', '1', '1', '1', '1', '/merchant/list.json,/merchant/remove.json,/merchant/update.json,/scenicSpot/merchantList.json,/merchant/approve.json,/merchant/distributeScenic.json,/merchant/cancelDistributeScenic.json,/merchant/getScenicSpotListByMerchant.json', '7');
INSERT INTO `RIGHT_MENUITEM` VALUES ('74', '订单管理', 'channelorderview', 'channel.ChannelOrderController', 'admin', '2013-10-24 23:20:21', 'orderBig', 'orderSmall', '1', '1', '1', '1', '/channel/order/list.json,/goodsCommon/getRelateGoodsList.json,/channel/order/travelDateList.json,/area/levelList.json,channel/order/saveGroupOrder.json,/channel/order/channelSettlePrice.json', '10');
INSERT INTO `RIGHT_MENUITEM` VALUES ('75', '景区管理', 'scenicspotview', 'operation.scenicspot.ScenicSpotController', 'admin', '2013-10-25 13:39:05', 'scenicBig', 'scenicSmall', '1', '1', '1', '1', '/scenicSpot/list.json,/scenicSpot/remove.json,/scenicSpot/update.json,/scenicSpot/approve.json,/scenicSpot/distributeSupplier.json,/scenicSpot/cancelDistributeSupplier.json,/scenicSpot/distributeMerchant.json,/scenicSpot/cancelDistributeMerchant.json,/merchant/getScenicSpotListByMerchant.json,/supplier/getScenicSpotListBySupplier.json', '7');
INSERT INTO `RIGHT_MENUITEM` VALUES ('78', '设备管理', 'equipmentview', 'scenic.equipment.EquipmentController', '', '2013-10-25 14:44:09', 'equipmentBig', 'equipmentSmall', '1', '1', '1', '1', '/equipment/equipmentList.json', '7');
INSERT INTO `RIGHT_MENUITEM` VALUES ('79', '系统管理', 'sysviewtwo', 'operation.system.SystemCodeController', 'admin', '2013-10-25 16:50:28', 'systemBig', 'systemSmall', '1', '1', '1', '1', '', '7');
INSERT INTO `RIGHT_MENUITEM` VALUES ('80', '评论管理', 'commentview', 'comment.CommentController', 'admin', '2013-10-28 17:07:34', 'commentBig', 'commentSmall', '1', '1', '1', '1', null, '9');
INSERT INTO `RIGHT_MENUITEM` VALUES ('83', '景区管理', 'buscenicspotview', 'bu.scenic.ScenicSpotController', 'admin', '2013-10-29 17:54:02', 'divisionBig', 'divisionSmall', '1', '1', '1', '1', '/buScenicSpot/list.json,/buScenicSpot/updateState.json,/buScenicSpot/update.json', '8');
INSERT INTO `RIGHT_MENUITEM` VALUES ('86', '商户管理 ', 'bumerchantview', 'bu.merchant.MerchantController', 'admin', '2013-10-29 19:50:16', 'merchantBig', 'merchantSmall', '1', '1', '1', '1', '/buMerchant/list.json,/buMerchant/updateMerchantState.json,/buMerchant/update.json', '8');
INSERT INTO `RIGHT_MENUITEM` VALUES ('89', '订单管理', 'operationorderview', 'operation.order.OperationOrderController', 'admin', '2013-10-30 18:24:01', 'orderBig', 'orderSmall', '1', '1', '1', '1', null, '7');
INSERT INTO `RIGHT_MENUITEM` VALUES ('93', '系统配置', 'configview', 'framework.ConfigController', 'admin', '2013-10-31 17:00:12', 'configurationBig', 'configurationSmall', '1', '1', '1', '1', '/config/list.json,/config/add.json,/config/update.json,config/remove.json', '1');
INSERT INTO `RIGHT_MENUITEM` VALUES ('95', '酒店管理', 'hotelview', 'scenic.HotelController', 'admin', '2013-11-05 14:11:07', 'hotelBig', 'hotelBigSmall', '1', '1', '1', '1', null, '9');
INSERT INTO `RIGHT_MENUITEM` VALUES ('96', '商户列表', 'scenicmerchantview', 'scenic.merchant.ScenicMerchantController', 'admin', '2013-11-05 16:55:51', 'merchantBig', 'merchantSmall', '1', '1', '1', '1', '/scenic/merchant/list.json,/scenic/merchant/remove.json', '9');
INSERT INTO `RIGHT_MENUITEM` VALUES ('100', '商品日程管理', 'goodsscheduleview', 'scenic.GoodsScheduleController', 'admin', '2013-11-06 11:10:58', 'scheduleBig', 'scheduleSmall', '1', '1', '1', '1', '/goodsSchedule/getGoodsScheduleListByPage.json,/goodsSchedule/addGoodsSchedule.json,/goodsSchedule/updateGoodsSchedule.json,/goodsSchedule/deleteGoodsSchedule.json,goodsCommon/getSelectTime.json', '9');
INSERT INTO `RIGHT_MENUITEM` VALUES ('102', '套餐管理', 'packageview', 'scenic.PackageController', 'admin', '2013-11-07 11:44:56', 'packagesBig', 'packagesSmall', '1', '1', '1', '1', '/goodsCommon/getPackageRelateGoodsList.json,/goodsCommon/findGoodsCommonList.json,/goodsCommon/saveScenicTicket.json,/goodsCommon/updateScenicTicket.json,/goodsCommon/delnGoods.json,/goodsCategory/findGoodsCategoryList.json,/goodsCategory/findGoodsCategoryList2.json,/goodsCategory/getGoodsCategornyListByParentId.json,/goodsCommon/getSupplierListByPage.json,/goodsCommon/getConsumeAreaList.json,/goodsCommon/getMerchantListnByPage.json,/goodsCommon/getRelateGoodsList.json,/goodsType/getAllGoodsTypeList.json,/goodsSchedule/getGoodsScheduleLisForCom.njson,/goodsCommon/getGoodsUseValidityList.json,/goodsCommon/getMyRelateGoodsList.json,/goodsCommon/getSmsModelList.json,/goodsCommon/getTicketModelList.json,/goodsCategory/getGoodsCategoryListByTypeCode.json,/goodsCommon/editGoodsCommon.json,/goodsCategory/getGoodsCategoryListByPage.json,/goodsCategory/addGoodsCategory.json,/goodsCategory/updateGoodsCategory.json,/goodsCategory/deleteGoodsCategory.json', '9');
INSERT INTO `RIGHT_MENUITEM` VALUES ('103', '团体订购', 'toAddChannelGroupOrder', 'toAddChannelGroupOrder', 'admin', '2013-11-07 20:12:48', 'demo-shortcut', 'icon-grid', '1', '1', '0', '0', '/channel/order/getPointDateUseValidityByGoodsId.json,/goodsCommon/getRelateGoodsListForChannel.json,/operation/system/getSystemCodeByType.json,/tourGuide/getGuideList.json,/area/levelList.json,/channel/order/saveGroupOrder.json', '74');
INSERT INTO `RIGHT_MENUITEM` VALUES ('105', '散客订购', 'toAddChannelSingleOrder', 'toAddChannelSingleOrder', 'admin', '2013-11-07 20:58:03', 'demo-shortcut', 'icon-grid', '2', '1', '1', '1', '/channel/order/saveSingleOrder.json', '74');
INSERT INTO `RIGHT_MENUITEM` VALUES ('106', '订单审核列表', 'toOrderAuditList', 'toOrderAuditList', 'admin', '2013-11-07 20:59:03', 'demo-shortcut', 'icon-grid', '4', '1', '1', '1', null, '74');
INSERT INTO `RIGHT_MENUITEM` VALUES ('107', '订单变更列表', 'toOrderChangeList', 'toOrderChangeList', 'admin', '2013-11-07 20:59:30', 'demo-shortcut', 'icon-grid', '3', '1', '1', '1', null, '74');
INSERT INTO `RIGHT_MENUITEM` VALUES ('110', '销售类报表', 't', 't', 'admin', '2013-11-08 11:46:11', 'demo-shortcut', '', '1', '1', '0', '0', null, '62');
INSERT INTO `RIGHT_MENUITEM` VALUES ('111', '销售订单明细', '1', '1', 'admin', '2013-11-08 11:48:16', 'demo-shortcut', 'icon-grid', '1', '1', '0', '0', null, '110');
INSERT INTO `RIGHT_MENUITEM` VALUES ('112', '销售订单明细', 'reportOrderAllInfo', 'reportOrderAllInfo', 'admin', '2013-11-08 11:51:29', 'crm-gly', 'icon-grid', '1', '1', '0', '0', '/report/org/getReportOrderAllInfo.json,/report/org/findSaleReportDetailByOrderNo.json', '111');
INSERT INTO `RIGHT_MENUITEM` VALUES ('113', '凭证管理', ' ', ' ', 'admin', '2013-11-08 15:49:29', 'demo-shortcut', 'icon-grid', '1', '1', '1', '1', null, '65');
INSERT INTO `RIGHT_MENUITEM` VALUES ('114', '凭证列表', 'getVoucherList', 'getVoucherList', 'admin', '2013-11-08 15:51:05', 'demo-shortcut', 'icon-grid', '1', '1', '1', '1', 'voucher/getVoucherList.json', '113');
INSERT INTO `RIGHT_MENUITEM` VALUES ('115', '退订', 'cancelVoucherList', 'cancelVoucherList', 'admin', '2013-11-08 15:52:22', 'demo-shortcut', 'icon-grid', '2', '1', '1', '1', 'voucher/cancelVoucherList.json', '113');
INSERT INTO `RIGHT_MENUITEM` VALUES ('116', '团体销售订单', 'groupOrderInfo', 'groupOrderInfo', 'admin', '2013-11-08 15:53:43', 'crm-gly', 'icon-grid', '2', '1', '0', '0', '/report/org/findSaleReportDetailByOrderNo.json,/report/org/getReportGroupOrderInfo.json', '111');
INSERT INTO `RIGHT_MENUITEM` VALUES ('117', 'OTA销售订单', 'otaOrderInfo', 'otaOrderInfo', 'admin', '2013-11-08 15:55:19', 'crm-gly', 'icon-grid', '3', '1', '0', '0', '/report/org/getOtaOrderInfo.json,/report/org/findSaleReportDetailByOrderNo.json', '111');
INSERT INTO `RIGHT_MENUITEM` VALUES ('118', 'WEB销售订单', 'webOrderInfo', 'webOrderInfo', 'admin', '2013-11-08 15:57:02', 'crm-gly', 'icon-grid', '4', '1', '0', '0', '/report/org/findSaleReportDetailByOrderNo.json,/report/org/getWebOrderInfo.json', '111');
INSERT INTO `RIGHT_MENUITEM` VALUES ('120', '销售数据统计', 'sss', 'ss', 'admin', '2013-11-08 16:02:55', 'demo-shortcut', '', '2', '1', '0', '0', null, '110');
INSERT INTO `RIGHT_MENUITEM` VALUES ('121', '日销售统计报表', 'reportStatisticsDay', 'reportStatisticsDay', 'admin', '2013-11-08 16:04:26', 'crm-gly', 'icon-grid', '1', '1', '0', '0', '/report/org/getProductReportStatistics/day.json,/report/org/getProductReportStatisticsPic/day.json', '120');
INSERT INTO `RIGHT_MENUITEM` VALUES ('122', '月销售统计报表', 'reportStatisticsMonth', 'reportStatisticsMonth', 'admin', '2013-11-08 16:06:28', 'crm-gly', 'icon-grid', '2', '1', '0', '0', '/report/org/getProductReportStatistics/month.json,/report/org/getProductReportStatisticsPic/month.json', '120');
INSERT INTO `RIGHT_MENUITEM` VALUES ('123', '销售时段统计报表', 'saleHourRange', 'saleHourRange', 'admin', '2013-11-08 16:10:09', 'crm-gly', 'icon-grid', '3', '1', '0', '0', '/report/org/getProductReportStatistics/hour.json,/report/org/getProductReportStatisticsPic/hour.json', '110');
INSERT INTO `RIGHT_MENUITEM` VALUES ('124', '销售频率报表', 'saleFrequency', 'saleFrequency', 'admin', '2013-11-08 16:11:12', 'crm-gly', 'icon-grid', '4', '1', '0', '0', '/report/org/findProductSaleRateByProductId.json,/report/org/getProductReportStatisticRatePage.json', '110');
INSERT INTO `RIGHT_MENUITEM` VALUES ('126', '运营类报表', 'qwe', 'qwe', 'admin', '2013-11-08 16:55:31', 'demo-shortcut', 'icon-grid', '3', '1', '0', '0', null, '62');
INSERT INTO `RIGHT_MENUITEM` VALUES ('127', '入园统计报表', 'forAdmissionReport', 'forAdmissionReport', 'admin', '2013-11-08 16:56:23', 'crm-gly', 'icon-grid', '1', '1', '0', '0', '/report/org/getStatisticsReportForAdmissionGood.json,/report/org/getReportForAdmissionPageAction.json', '126');
INSERT INTO `RIGHT_MENUITEM` VALUES ('128', '报表后台任务', 'bbhtrw12213@', 'bbhtrw', 'admin', '2013-11-08 16:57:07', 'demo-shortcut', 'icon-grid', '4', '1', '0', '0', 'org/reRunProductStatisticReport.json', '62');
INSERT INTO `RIGHT_MENUITEM` VALUES ('129', '报表后台操作', 'reportTask', 'reportTask', 'admin', '2013-11-08 16:57:43', 'demo-shortcut', 'icon-grid', '1', '1', '0', '0', null, '128');
INSERT INTO `RIGHT_MENUITEM` VALUES ('133', '高尔夫管理', 'golfview', 'scenic.GolfController', 'admin', '2013-11-08 21:44:37', 'scheduleBig', 'scheduleSmall', '1', '1', '1', '1', null, '9');
INSERT INTO `RIGHT_MENUITEM` VALUES ('137', '渠道管理', 'qdgl', ' ', 'admin', '2013-11-09 14:45:02', 'demo-shortcut', '', '1', '1', '0', '0', null, '63');
INSERT INTO `RIGHT_MENUITEM` VALUES ('138', '未签约的渠道', 'channelList', 'channelList', 'admin', '2013-11-09 14:45:42', 'crm-gly', '', '2', '1', '0', '0', 'channel/getChannelByPage.json,channel/updateSignChannelScenic.json', '137');
INSERT INTO `RIGHT_MENUITEM` VALUES ('139', '已签约的渠道', 'channelscenicList', 'channelscenicList', 'admin', '2013-11-09 16:25:15', 'crm-caidan', '', '2', '1', '0', '0', 'channel/getChannelScenicByPage.json,channel/updateChannelStatus.json,channel/auditingChannel.json,channel/getChannelAccountList.json,channel/updateAccountIsDelete.json,channel/updateAccountStatus.json,channel/updateWarning.json,channel/saveJournal.json,channel/getChannelProduct.json,channel/auditingChannelProduct.json,channel/removeChannelProduct.json,channel/updateChannelProductPrice.json,channel/updateChannelProduct.json,channel/getChannelNoProduct.json,channel/saveChannelProducts.json,channel/getClientByPage.json,channel/updateClient.json,channel/freezeClient.json,channel/auditingChannelScenic.json,channel/saveClient.json,channel/getAccountByChannelId.json,levelList.json,channel/auditingNotChannelProduct.json', '137');
INSERT INTO `RIGHT_MENUITEM` VALUES ('140', '签约记录', 'signContractList', 'signContractList', 'admin', '2013-11-09 16:27:16', 'crm-gly', '', '2', '1', '0', '0', 'channel/getChannelScenicSpot.json,channel/auditingChannelScenic.json,channel/freezeChannelScenic.json,channel/DetilChannelScenic.json', '137');
INSERT INTO `RIGHT_MENUITEM` VALUES ('141', '预付款账户', 'yfkzh', ' ', 'admin', '2013-11-09 16:29:09', 'demo-shortcut', '', '1', '1', '1', '1', null, '63');
INSERT INTO `RIGHT_MENUITEM` VALUES ('142', '交易记录', 'accountJournalList', 'accountJournalList', 'admin', '2013-11-09 16:30:26', 'crm-gly', '', '2', '1', '0', '0', 'channel/getAccountJournalList.json,channel/updateJournal.json,channel/getChannelAccountById.json', '141');
INSERT INTO `RIGHT_MENUITEM` VALUES ('143', '手续费规则管理', 'showFeeList', 'showFeeList', 'admin', '2013-11-11 16:45:45', 'demo-shortcut', 'icon-grid', '1', '1', '0', '0', null, '68');
INSERT INTO `RIGHT_MENUITEM` VALUES ('144', '运营商规则管理', 'showCarrierList', 'showCarrierList', 'admin', '2013-11-11 17:09:06', 'demo-shortcut', 'icon-grid', '2', '1', '0', '0', null, '68');
INSERT INTO `RIGHT_MENUITEM` VALUES ('145', '渠道商规则管理', 'showChannelList', 'showChannelList', 'admin', '2013-11-11 17:09:41', 'demo-shortcut', 'icon-grid', '3', '1', '0', '0', null, '68');
INSERT INTO `RIGHT_MENUITEM` VALUES ('146', '支付渠道商规则管理', 'showPayChannelList', 'showPayChannelList', 'admin', '2013-11-11 17:10:25', 'crm-gly', 'icon-grid', '4', '1', '0', '0', ' ', '68');
INSERT INTO `RIGHT_MENUITEM` VALUES ('148', '高尔夫管理', 'gefgl', ' ', 'admin', '2013-11-12 11:24:04', 'scheduleBig', 'scheduleSmall', '2', '1', '0', '0', ' ', '133');
INSERT INTO `RIGHT_MENUITEM` VALUES ('149', '高尔夫列表', 'golfListAction', 'golfListAction', 'admin', '2013-11-12 11:28:08', 'crm-gly', 'icon-grid', '3', '1', '1', '0', '/golfMuseum/findGolfByPage.json,/golfMuseum/saveGolf.json,/golfMuseum/updateGolf.json,/golfMuseum/deleteGolf.json,/golfMuseum/updateCheckStatus.json,/golfMuseum/updateStatus.json', '148');
INSERT INTO `RIGHT_MENUITEM` VALUES ('154', '高尔夫门票', 'gefmp', ' ', 'admin', '2013-11-12 11:41:57', 'crm-gly', 'icon-grid', '1', '1', '1', '0', ' ', '133');
INSERT INTO `RIGHT_MENUITEM` VALUES ('155', '门票列表', 'golfTicketListAction', 'golfTicketListAction', 'admin', '2013-11-12 11:43:32', 'crm-gly', 'icon-grid', '2', '1', '1', '0', '/goodsCommon/findGoodsCommonList.json?goodsTypeCode=GOLF,/golfMuseum/findGolfAll.json,/golfTicket/saveGolfTicket.json,/golfTicket/updateGolfTicket.json,/goodsCommon/delGoods.json,/goodsCommon/getSupplierListByPage.json,/goodsCommon/getConsumeAreaList.json,goodsCommon/getMerchantListByPage.json', '154');
INSERT INTO `RIGHT_MENUITEM` VALUES ('156', '分类管理', 'flgl2', ' ', 'admin', '2013-11-12 11:49:37', 'crm-gly', 'icon-grid', '1', '1', '1', '0', ' ', '133');
INSERT INTO `RIGHT_MENUITEM` VALUES ('157', '分类列表', 'golfTicketCategoryListAction', 'golfTicketCategoryListAction', 'admin', '2013-11-12 11:51:57', 'crm-gly', 'icon-grid', '2', '1', '1', '0', 'goodsCategory/getGoodsCategoryListByPage.json,goodsCategory/getCategoryByTypeCode.json', '156');
INSERT INTO `RIGHT_MENUITEM` VALUES ('165', '酒店管理', 'jdgl', ' ', 'admin', '2013-11-12 13:52:25', 'crm-gly', 'icon-grid', '1', '1', '1', '0', ' ', '95');
INSERT INTO `RIGHT_MENUITEM` VALUES ('166', '酒店列表', 'hotelListAction', 'hotelListAction', 'admin', '2013-11-12 13:53:37', 'crm-gly', 'icon-grid', '2', '1', '0', '0', 'hotel/findHotelByPage.json,hotel/saveHotel.json,hotel/updateHotel.json,hotel/deleteHotel.json,hotel/updateCheckStatus.json,hotel/updateStatus.json,hotel/editHotel.json', '165');
INSERT INTO `RIGHT_MENUITEM` VALUES ('167', '散客订单列表', 'toChannelSingleOrderList', 'toChannelSingleOrderList', 'admin', '2013-11-12 14:33:48', 'crm-gly', 'icon-grid', '4', '1', '0', '0', 'toChannelSingleOrderList', '74');
INSERT INTO `RIGHT_MENUITEM` VALUES ('174', '房型管理', 'fxgl', ' ', 'admin', '2013-11-12 15:39:31', 'crm-gly', 'icon-grid', '1', '1', '0', '0', ' ', '95');
INSERT INTO `RIGHT_MENUITEM` VALUES ('178', '房型列表', 'hotelRoomListAction', 'hotelRoomListAction', 'admin', '2013-11-12 15:47:33', 'crm-gly', 'icon-grid', '2', '1', '0', '0', 'goodsCommon/findGoodsCommonList.json?goodsTypeCode=HOTEL,hotelRoom/saveHotelRoom.json,hotelRoom/updateHotelRoom.json,goodsCommon/delGoods.json,hotel/findHotelAll.json', '174');
INSERT INTO `RIGHT_MENUITEM` VALUES ('180', '渠道商管理', 'cchannelview', 'channel.ChannelController', 'admin', '2013-11-12 15:43:43', 'channelBig', 'channelSmall', '0', '1', '1', '1', '/channel/getChannelDetailId.json', '10');
INSERT INTO `RIGHT_MENUITEM` VALUES ('181', '房型分类', 'fxfl', ' ', 'admin', '2013-11-12 16:16:57', 'crm-gly', 'icon-grid', '1', '1', '1', '1', ' ', '95');
INSERT INTO `RIGHT_MENUITEM` VALUES ('182', '分类列表', 'hoteRoomCategoryListAction', 'hoteRoomCategoryListAction', 'admin', '2013-11-12 16:22:37', 'crm-gly', 'icon-grid', '2', '1', '0', '0', 'goodsCategory/getGoodsCategoryListByPage.json,goodsCategory/getCategoryByTypeCode.json', '181');
INSERT INTO `RIGHT_MENUITEM` VALUES ('183', '剧院管理', 'theaterview', 'scenic.TheaterController', 'admin', '2013-11-12 16:34:25', 'theaterBig', 'theaterSmall', '1', '1', '1', '1', ' ', '9');
INSERT INTO `RIGHT_MENUITEM` VALUES ('184', '剧院管理', 'jygl', ' ', 'admin', '2013-11-12 16:35:43', 'crm-gly', 'icon-grid', '1', '1', '1', '0', ' ', '183');
INSERT INTO `RIGHT_MENUITEM` VALUES ('185', '剧院列表', 'theaterListAction', 'theaterListAction', 'admin', '2013-11-12 16:36:55', 'crm-gly', 'icon-grid', '2', '1', '1', '0', '/theater/findTheaterByPage.json,/theater/saveTheater.json,/theater/updateTheater.json,/theater/deleteTheater.json,/theater/updateCheckStatus.json,/theater/updateStatus.json,theater/checkTheaterIsShanJia.json', '184');
INSERT INTO `RIGHT_MENUITEM` VALUES ('186', '剧票管理', 'jpgl', ' ', 'admin', '2013-11-12 17:01:08', 'crm-gly', 'icon-grid', '1', '1', '1', '0', 'hotel/findHotelByPage.json,hotel/saveHotel.json,hotel/updateHotel.json,hotel/deleteHotel.json,hotel/updateCheckStatus.json,hotel/updateStatus.json', '183');
INSERT INTO `RIGHT_MENUITEM` VALUES ('187', '剧票列表', 'theaterTicketListAction', 'theaterTicketListAction', 'admin', '2013-11-12 17:02:10', 'crm-gly', 'icon-grid', '2', '1', '1', '0', 'goodsCommon/findGoodsCommonList.json?goodsTypeCode=THEATER,/theaterTicket/saveTheaterTicket.json,/theaterTicket/updateTheaterTicket.json,/goodsCommon/delGoods.json,/goodsCommon/updateCheckStatus.json,/goodsCommon/updateFinanceCheckStatus.json,/goodsCommon/updateStatus.json,/theater/findTheaterAll.json,/goodsCommon/getConsumeAreaList.json,goodsCommon/getMerchantListByPage.json,/goodsCommon/getSupplierListByPage.json', '186');
INSERT INTO `RIGHT_MENUITEM` VALUES ('188', '剧票分类', 'jpfl', ' ', 'admin', '2013-11-12 17:03:20', 'crm-gly', 'icon-grid', '1', '1', '1', '0', ' ', '183');
INSERT INTO `RIGHT_MENUITEM` VALUES ('189', '分类列表', 'theaterTicketCategoryAction', 'theaterTicketCategoryAction', 'admin', '2013-11-12 17:08:21', 'crm-gly', 'icon-grid', '2', '1', '1', '0', 'goodsCategory/getGoodsCategoryListByPage.json,goodsCategory/getCategoryByTypeCode.json', '188');
INSERT INTO `RIGHT_MENUITEM` VALUES ('190', '团体订单列表', 'grouporderlist', 'grouporderlist', 'admin', '2013-11-12 20:45:29', '', '', '5', '1', '0', '0', '/order/all.json,/order/cancelOrder.json,/channel/order/orderSelfAudit.json,/operation/system/getSystemCodeByType.json,/orderData/getDatas.json,/orderData/save.json,/orderData/update.json,/orderData/del.json,voucher/cancelVoucherList.json', '65');
INSERT INTO `RIGHT_MENUITEM` VALUES ('193', '散客订单', 'orderlistBySan', 'orderlistBySan', 'admin', '2013-11-12 23:41:24', 'orderBig', 'orderSmall', '4', '1', '1', '1', 'order/pages.json,voucher/cancelVoucherList.json,operation/system/getSystemCodeByType.json', '65');
INSERT INTO `RIGHT_MENUITEM` VALUES ('194', '预付款账户', 'yfkzhl', '2', 'admin', '2013-11-13 12:02:52', 'channelBig', 'channelSmall', '1', '1', '1', '1', '3', '180');
INSERT INTO `RIGHT_MENUITEM` VALUES ('195', '预付款账户列表', 'cAccountlList', 'cAccountlList', 'admin', '2013-11-13 14:44:28', 'channelBig', 'channelSmall', '2', '1', '1', '1', 'channel/findChannelAccountList.json', '194');
INSERT INTO `RIGHT_MENUITEM` VALUES ('196', '交易记录列表', 'caccountJournalList', 'caccountJournalList', 'admin', '2013-11-13 16:13:21', 'channelBig', 'channelSmall', '2', '1', '1', '1', 'channel/getAccountJournalList.json,channel/findChannelProduct.json', '194');
INSERT INTO `RIGHT_MENUITEM` VALUES ('199', '商品列表', 'cchannelproductlist', 'cchannelProductlist', 'admin', '2013-11-14 11:51:50', 'channelBig', 'channelSmall', '1', '1', '1', '1', 'channel/findChannelProduct.json,channel/updateChannelProductPrice.json', '180');
INSERT INTO `RIGHT_MENUITEM` VALUES ('203', '业务配置', 'ywgl2', '2', 'admin', '2013-11-14 15:48:53', 'systemBig', 'systemSmall', '1', '1', '1', '1', '2', '79');
INSERT INTO `RIGHT_MENUITEM` VALUES ('204', '数据字典', 'systemcodelist2', 'systemCode', 'admin', '2013-11-14 15:52:20', 'systemBig', 'systemSmall', '2', '1', '1', '1', 'operation/system/getSystemCodeByPage.json', '203');
INSERT INTO `RIGHT_MENUITEM` VALUES ('205', '模板', 'mouldlist', 'mouldCode', 'admin', '2013-11-14 15:54:54', 'systemBig', 'systemSmall', '2', '1', '1', '1', 'operation/system/getMouldByPage.json', '203');
INSERT INTO `RIGHT_MENUITEM` VALUES ('207', '入园记录', 'ryjl', '2', 'admin', '2013-11-15 15:18:06', 'channelBig', 'channelSmall', '1', '1', '1', '1', '2', '63');
INSERT INTO `RIGHT_MENUITEM` VALUES ('208', '入园记录列表', 'terminalrecordlist', 'terminalrecordlist', 'admin', '2013-11-15 15:20:03', 'channelBig', 'channelSmall', '2', '1', '1', '1', 'channel/getTerminalRecordByPage.json', '207');
INSERT INTO `RIGHT_MENUITEM` VALUES ('212', '渠道商管理', 'ochannelview', 'operation.channel.ChannelController', 'admin', '2013-11-19 20:46:23', 'channelBig', 'channelSmall', '1', '1', '1', '1', '', '7');
INSERT INTO `RIGHT_MENUITEM` VALUES ('221', '系统管理', 'sysview2', 'operation.system.SystemCodeController', 'admin', '2013-11-22 16:29:34', 'configurationBig', 'configurationSmall', '1', '1', '1', '1', ' ', '9');
INSERT INTO `RIGHT_MENUITEM` VALUES ('222', '业务配置', 'ywpz', '2', 'admin', '2013-11-22 16:48:05', 'systemBig', 'systemSmall', '1', '1', '1', '1', '2', '221');
INSERT INTO `RIGHT_MENUITEM` VALUES ('223', '数据字典', 'systemcodelist22', 'systemCode', 'admin', '2013-11-22 16:49:26', 'systemBig', 'systemSmall', '2', '1', '1', '1', 'operation/system/getSystemCodeByPage.json', '222');
INSERT INTO `RIGHT_MENUITEM` VALUES ('224', '模板', 'mouldlist2', 'mouldCode', 'admin', '2013-11-22 16:50:28', 'systemBig', 'systemSmall', '2', '1', '1', '1', 'operation/system/getMouldByPage.json', '222');
insert into `RIGHT_MENUITEM` (`MENU_ID`, `MENU_NAME`, `MENU_W_NAME`, `MENU_ACTION`, `CREATE_USER`, `CREATE_DATE`, `MENU_ICON_CLS`, `MENU_SMALL_CLS`, `MENU_PRIORITY`, `MENU_STATUS`, `MENU_STARTMENU`, `MENU_QUICKMENU`, `MENU_URL`, `MAIN_MENU_ID`) values('225','凭证管理','pzglsw','','admin','2013-11-18 21:35:38','channelBig','channelSmall','2','1','1','1','','89');
insert into `RIGHT_MENUITEM` (`MENU_ID`, `MENU_NAME`, `MENU_W_NAME`, `MENU_ACTION`, `CREATE_USER`, `CREATE_DATE`, `MENU_ICON_CLS`, `MENU_SMALL_CLS`, `MENU_PRIORITY`, `MENU_STATUS`, `MENU_STARTMENU`, `MENU_QUICKMENU`, `MENU_URL`, `MAIN_MENU_ID`) values('226','凭证列表','operationvoucherlist','getVoucherList','admin','2013-11-18 21:36:41','channelBig','channelSmall','2','1','1','1','operationVoucher/getVoucherListByOperation.json','225');
insert into `RIGHT_MENUITEM` (`MENU_ID`, `MENU_NAME`, `MENU_W_NAME`, `MENU_ACTION`, `CREATE_USER`, `CREATE_DATE`, `MENU_ICON_CLS`, `MENU_SMALL_CLS`, `MENU_PRIORITY`, `MENU_STATUS`, `MENU_STARTMENU`, `MENU_QUICKMENU`, `MENU_URL`, `MAIN_MENU_ID`) values('227','凭证管理','pzglsw2','  ','admin','2013-11-26 15:27:36','orderBig','orderSmall','5','1','1','1','','74');
insert into `RIGHT_MENUITEM` (`MENU_ID`, `MENU_NAME`, `MENU_W_NAME`, `MENU_ACTION`, `CREATE_USER`, `CREATE_DATE`, `MENU_ICON_CLS`, `MENU_SMALL_CLS`, `MENU_PRIORITY`, `MENU_STATUS`, `MENU_STARTMENU`, `MENU_QUICKMENU`, `MENU_URL`, `MAIN_MENU_ID`) values('228','凭证列表','channelVoucherList','channelVoucherList','admin','2013-11-26 15:28:31','orderBig','orderSmall','1','1','1','1','channelVoucher/getVoucherListByChannel.json','227');


INSERT INTO `RIGHT_OPERATE` VALUES ('1', '删除菜单', 'admin', '2013-10-21 21:26:40', 'delMenuItem', '0', 'menuItemDelButton', '删除菜单', '/framework/menuItem/del.json', '5', '2');
INSERT INTO `RIGHT_OPERATE` VALUES ('2', '添加菜单', 'admin', '2013-10-21 21:27:58', 'addMenuItem', '1', 'menuItemAddButton', '添加菜单', '/menuItem/saveOrUpdateMenuItem.json', '5', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('3', '编辑菜单', 'admin', '2013-10-21 21:29:21', 'editMenuItem', '0', 'menuItemEditButton', '编辑菜单', '/role/getMenuTree.json,/role/getRoleTree.json,/menuItem/saveOrUpdateMenuItem.json', '5', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('4', '删除操作', 'admin', '2013-10-22 16:47:22', 'delOperate', '0', 'operateDelButton', '删除操作', '/operate/del.json', '2', '2');
INSERT INTO `RIGHT_OPERATE` VALUES ('5', '添加操作', 'admin', '2013-10-22 16:49:23', 'addOperate', '1', 'operateAddButton', '添加操作', '/role/getMenuTree.json', '2', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('6', '编辑操作', 'admin', '2013-10-22 16:49:53', 'editOperate', '0', 'operateEditButton', '修改操作', '/role/getMenuTree.json,/operate/saveOrUpdateOperate.json', '2', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('7', '添加子角色', 'admin', '2013-10-22 16:54:47', 'addRole', '1', 'roleAddButton', '添加子角色', '/role/addRole.json,/role/getMenuTree.json', '4', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('8', '编辑角色', 'admin', '2013-10-22 17:08:26', 'editRole', '0', 'roleEditButton', '编辑角色', '/role/editRole.json,/role/getMenuTree.json', '4', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('9', '删除角色', 'admin', '2013-10-22 17:21:25', 'delRole', '0', 'roleDelButton', '删除角色', '/role/delRole.json', '4', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('10', '添加分组', 'admin', '2013-10-22 17:30:48', 'addGroup', '1', 'groupAddButton', '添加分组', '/group/add.json,/role/getRoleTree.json,/group/getGroupTree.json', '3', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('11', '修改分组', 'admin', '2013-10-22 17:31:18', 'editGroup', '0', 'groupEditButton', '修改分组', '/group/edit.json,/role/getRoleTree.json,/group/getGroupTree.json', '3', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('12', '删除分组', 'admin', '2013-10-22 17:31:43', 'delGroup', '0', 'groupDelButton', '删除分组', '/group/remove.json', '3', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('13', '删除成员', 'admin', '2013-10-22 18:06:08', 'delMember', '0', 'memberdelbutton', '删除成员', null, '6', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('14', '添加成员', 'admin', '2013-10-22 18:10:19', 'addMember', '1', 'memberaddbutton', '添加成员', null, '6', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('15', '编辑成员', 'admin', '2013-10-22 18:10:42', 'editMember', '1', 'membereditbutton', '编辑成员', null, '6', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('20', '添加类型', 'admin', '2013-11-27 03:41:05', 'addRole', '1', '', '', '/role/addRole.json,/role/getMenuTree.json', '26', '10');
INSERT INTO `RIGHT_OPERATE` VALUES ('21', '编辑类型', 'admin', '2013-11-27 03:41:36', 'editRole', '1', '', '', '/role/editRole.json,/role/getMenuTree.json', '26', '20');
INSERT INTO `RIGHT_OPERATE` VALUES ('22', '删除类型', 'admin', '2013-11-27 03:42:01', 'delRole', '1', '', '', '/role/delRole.json', '26', '30');
INSERT INTO `RIGHT_OPERATE` VALUES ('23', '暂停/恢复', 'admin', '2013-11-27 03:42:01', 'pauseTask', '0', '', '', '/task/triggerStatus.json', '12', '1');



INSERT INTO `RIGHT_OPERATE` VALUES ('37', '新增渠道商', 'admin', '2013-11-11 17:19:49', 'addChannel', '1', 'addChannel', '新增渠道商', 'channel/save.json', '139', '5');
INSERT INTO `RIGHT_OPERATE` VALUES ('38', '编辑事业部', 'admin', '2013-10-24 16:14:58', 'editBusiness', '0', 'editBusiness', '修改事业部信息', null, '69', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('39', '删除景区', 'admin', '2013-10-25 14:47:19', 'delScenicSpot', '0', 'delScenicSpot', '运营商后台删除景区信息<br>', null, '75', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('41', '删除事业部', 'admin', '2013-10-25 15:05:36', 'delBusiness', '0', 'delBusiness', '运营商后台删除事业部<br>', null, '69', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('42', '删除机构', 'admin', '2013-10-25 15:56:40', 'delInst', '0', 'delInst', '运营商后台机构管理列表删除机构<br>', null, '44', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('43', '编辑机构', 'admin', '2013-10-25 15:57:16', 'editInst', '1', 'editInst', '运营商后台机构管理列表编辑机构<br>', null, '44', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('44', '添加机构', 'admin', '2013-10-25 15:59:24', 'addInst', '1', 'addInst', '运营商后台机构管理列表添加机构', null, '44', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('45', '删除供应商', 'admin', '2013-10-25 16:06:40', 'delSupplier', '0', 'delSupplier', '运营商后台供应商列表删除供应商', null, '72', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('46', '编辑供应商', 'admin', '2013-10-25 16:07:13', 'editSupplier', '0', 'editSupplier', '运营商后台供应商列表编辑供应商', null, '72', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('47', '删除商户', 'admin', '2013-10-25 16:09:53', 'delMerchant', '0', 'delMerchant', '运营商后台商户列表删除商户', null, '73', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('48', '编辑商户', 'admin', '2013-10-25 16:10:24', 'editMerchant', '0', 'editMerchant', '运营商后台商户列表编辑商户', null, '73', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('49', '编辑景区', 'admin', '2013-10-25 17:54:31', 'editScenicSpot', '0', 'editScenicSpot', '运营商后台景区列表编辑景区', null, '75', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('51', '删除剧票', 'admin', '2013-10-28 17:55:10', 'delTheaterTicketAction', '0', 'delTheaterTicketAction', '景区后台——剧院管理——剧票列表 ：删除剧票<br>', null, '187', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('52', '编辑剧票', 'admin', '2013-10-28 17:55:43', 'editTheaterTicketAction', '0', 'editTheaterTicketAction', '景区后台——剧院管理——剧票列表 ：编辑剧票<br>', null, '187', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('53', '添加剧票', 'admin', '2013-10-28 17:55:59', 'addTheaterTicketAction', '1', 'addTheaterTicketAction', '景区后台——剧院管理——剧票列表 ：添加剧票<br>', ' ', '187', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('54', '添加商品', 'admin', '2013-10-29 15:44:56', 'addGoodsCommon', '1', 'addGoodsCommon', '通用商品管理<br>', null, '43', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('55', '删除商品', 'admin', '2013-10-29 15:45:34', 'delGoodsCommon', '0', 'delGoodsCommon', '通用商品管理<br>', null, '43', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('56', '编辑商品', 'admin', '2013-10-29 15:45:50', 'editGoodsCommon', '0', 'editGoodsCommon', '通用商品管理<br>', null, '43', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('57', '商品分类管理', 'admin', '2013-10-29 15:52:59', 'goodsCategoryManager', '1', 'goodsCategoryManager', '通用商品管理——商品分类管理', null, '43', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('58', '删除景区', 'admin', '2013-10-29 20:58:36', 'delScenicSpot', '0', 'delScenicSpotBtn', '', null, '83', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('60', '删除商户', 'admin', '2013-10-29 21:12:50', 'delMerchant', '0', 'delMerchantBtn', '', null, '86', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('68', '查看详细', 'admin', '2013-10-31 11:17:12', 'scenicSpotDetail', '0', 'scenicSpotDetailBtn', '', null, '83', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('69', '查看详情', 'admin', '2013-10-31 13:35:59', 'merchantDetail', '0', 'merchantDetailBtn', '', null, '86', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('71', '添加系统配置', 'admin', '2013-10-31 17:31:36', 'addConfig', '1', 'configaddbutton', '添加系统配置', null, '93', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('72', '编辑系统配置', 'admin', '2013-10-31 17:33:56', 'editConfig', '1', 'configeditbutton', '编辑系统配置', null, '93', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('73', '删除类型', 'admin', '2013-11-01 10:13:27', 'delGoodsTypeAction', '0', 'delGoodsTypeAction', '商品类型管理——删除操作', null, '56', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('74', '编辑类型', 'admin', '2013-11-01 10:15:16', 'editGoodsTypeAction', '0', 'editGoodsTypeAction', '商品类型管理—— <br>', null, '56', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('75', '添加类型', 'admin', '2013-11-01 10:15:44', 'addGoodsTypeAction', '1', 'addGoodsTypeAction', '商品类型管理—— addGoodsTypeAction<br>', null, '56', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('76', '删除剧院', 'admin', '2013-11-01 10:23:24', 'delTheaterAction', '0', 'delTheaterAction', '剧院管理——', null, '185', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('77', '编辑剧院', 'admin', '2013-11-01 10:23:51', 'editTheaterAction', '0', 'editTheaterAction', '剧院管理——editTheaterAction', ' ', '185', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('78', '添加剧院', 'admin', '2013-11-01 10:24:06', 'addTheaterAction', '1', 'addTheaterAction', '剧院管理——addTheaterAction', null, '185', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('79', '添加', 'admin', '2013-11-02 16:40:26', 'addTourGuide', '1', 'addTourGuideBtn', '<br>', null, '61', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('80', '编辑', 'admin', '2013-11-02 16:41:00', 'editTourGuide', '0', 'tourGuideEditBtn', '<br>', null, '61', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('81', '加入黑名单', 'admin', '2013-11-02 16:41:19', 'addBlackTourGuide', '0', 'tourGuideBlackBtn', '<br>', null, '61', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('82', '删除', 'admin', '2013-11-02 16:41:44', 'delTourGuide', '0', 'tourGuideDelBtn', '<br>', null, '61', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('83', '销售订单明细查询', 'admin', '2013-11-08 12:03:22', 'reportOrderAllInfo', '1', 'reportOrderAllInfo', '销售订单明细查询', null, '112', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('85', '删除日程', 'admin', '2013-11-11 14:25:43', 'delGoodsSchedule', '0', 'delGoodsSchedule', '景区 后台——delGoodsSchedule<br>', '/goodsSchedule/deleteGoodsSchedule.json', '100', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('86', '编辑日程', 'admin', '2013-11-11 14:26:19', 'toEditGoodsSchedule', '0', 'toEditGoodsSchedule', '景区 后台——toEditGoodsSchedule<br>', '/goodsSchedule/updateGoodsSchedule.json', '100', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('87', '添加日程', 'admin', '2013-11-11 14:26:42', 'toAddGoodsSchedule', '1', 'toAddGoodsSchedule', '景区 后台——toAddGoodsSchedule<br>', '/goodsSchedule/addGoodsSchedule.json', '100', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('88', '删除渠道商', 'admin', '2013-11-11 16:29:58', 'delMenuItem', '0', 'delMenuItem', '删除渠道商', 'channel/remove.json', '139', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('89', '编辑渠道', 'admin', '2013-11-11 17:19:49', 'editChannel', '0', 'editChannel', '编辑渠道', 'channel/update.json', '139', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('90', '删除手续费规则', 'admin', '2013-11-11 17:23:54', 'del', '1', 'del', '手续费规则--删除操作', null, '143', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('91', '删除', 'admin', '2013-11-11 17:54:59', 'deleteGolfAction', '0', 'deleteGolfAction', '删除', '545俄', '149', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('92', '删除商品', 'admin', '2013-11-11 18:03:32', 'delScenicTicket', '0', 'delScenicTicket', '删除景区门票', null, '49', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('93', '编辑商品', 'admin', '2013-11-11 18:03:56', 'editScenicTicket', '0', 'editScenicTicket', '编辑景区门票', null, '49', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('94', '添加商品', 'admin', '2013-11-11 18:04:27', 'toAddScenicTicket', '1', 'toAddScenicTicket', '添加景区门票', null, '49', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('95', '商品分类管理', 'admin', '2013-11-11 18:04:46', 'scenicTicketCategory', '1', 'scenicTicketCategory', '商品分类管理', null, '49', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('96', '删除分类', 'admin', '2013-11-11 21:00:39', 'delGoodsCategory', '0', 'delGoodsCategory', '啊啊啊', null, '49', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('97', '编辑分类', 'admin', '2013-11-11 21:17:50', 'editGoodsCategory', '0', 'editGoodsCategory', '编辑景区门票分类', null, '49', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('98', '添加分类', 'admin', '2013-11-11 21:23:30', 'toAddGoodsCategory', '1', 'toAddGoodsCategory', '<br>', null, '49', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('100', '编辑', 'admin', '2013-11-11 21:42:13', 'editGolfAction', '0', 'editGolfAction', 'editGolfActioneditGolfAction', 'golfMuseum/editGolf.json', '149', '2');
INSERT INTO `RIGHT_OPERATE` VALUES ('101', '添加', 'admin', '2013-11-11 21:44:25', 'addGolfAction', '1', 'addGolfAction', 'addGolfActionaddGolfAction', '  ', '149', '3');
INSERT INTO `RIGHT_OPERATE` VALUES ('102', '删除', 'admin', '2013-11-11 21:48:07', 'delGolfTicketAction', '0', 'delGolfTicketAction', 'delGolfTicketAction', ' ', '155', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('103', '编辑', 'admin', '2013-11-11 21:49:24', 'editGolfTicketAction', '0', 'editGolfTicketAction', '高尔夫管理——高尔夫商品<br>', ' goodsCommon/editGoodsCommon.json', '155', '2');
INSERT INTO `RIGHT_OPERATE` VALUES ('104', '添加', 'admin', '2013-11-11 21:50:03', 'addGolfTicketAction', '1', 'addGolfTicketAction', '高尔夫管理-高尔夫商品', ' ', '155', '3');
INSERT INTO `RIGHT_OPERATE` VALUES ('105', '删除', 'admin', '2013-11-12 10:18:41', 'delGoodsCategoryGolf', '0', 'delGoodsCategoryGolf', '高尔夫管理', ' ', '157', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('106', '编辑', 'admin', '2013-11-12 10:19:11', 'editGoodsCategoryGolf', '0', 'editGoodsCategoryGolf', 'editGoodsCategoryGolf', ' ', '157', '2');
INSERT INTO `RIGHT_OPERATE` VALUES ('107', '添加', 'admin', '2013-11-12 10:19:43', 'toAddGoodsCategoryGolf', '1', 'toAddGoodsCategoryGolf', 'toAddGoodsCategoryGolf', ' ', '157', '3');
INSERT INTO `RIGHT_OPERATE` VALUES ('108', '新增关联商品', 'admin', '2013-11-12 11:18:41', 'channelNotProduct', '1', 'channelNotProduct', '&nbsp; &nbsp;', '  ', '139', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('109', '删除', 'admin', '2013-11-12 14:26:07', 'deleteHotelAction', '0', 'deleteHotelAction', 'deleteHotelAction', ' ', '166', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('110', '编辑', 'admin', '2013-11-12 14:26:23', 'editHotelAction', '0', 'editHotelAction', 'editHotelAction', ' hotel/editHotel.json', '166', '2');
INSERT INTO `RIGHT_OPERATE` VALUES ('111', '添加', 'admin', '2013-11-12 14:27:28', 'addHotelAction', '1', 'addHotelAction', 'editHotelAction', ' ', '166', '3');
INSERT INTO `RIGHT_OPERATE` VALUES ('112', '新增客户端', 'admin', '2013-11-12 14:44:24', 'addChannelClient', '1', 'addChannelClient', '12', 'channel/saveClient.json', '139', '4');
INSERT INTO `RIGHT_OPERATE` VALUES ('113', '删除套餐', 'admin', '2013-11-12 14:50:14', 'delPackage', '0', 'delPackage', '&nbsp;', '/goodsCommon/delGoods.json', '102', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('116', '套餐分类管理', 'admin', '2013-11-12 15:33:20', 'packageCategory', '1', 'packageCategory', '', '/goodsCategory/getGoodsCategoryListByPage.json', '102', '4');
INSERT INTO `RIGHT_OPERATE` VALUES ('117', '删除分类', 'admin', '2013-11-12 15:35:29', 'delGoodsCategoryPackage', '0', 'delGoodsCategoryPackage', '&nbsp;', '/goodsCategory/deleteGoodsCategory.json', '102', '5');
INSERT INTO `RIGHT_OPERATE` VALUES ('118', '编辑分类', 'admin', '2013-11-12 15:36:33', 'editGoodsCategoryPackage', '1', 'editGoodsCategoryPackage', '&nbsp;', '/goodsCategory/updateGoodsCategory.json', '102', '6');
INSERT INTO `RIGHT_OPERATE` VALUES ('119', '添加分类', 'admin', '2013-11-12 15:42:20', 'toAddGoodsCategoryPackage', '1', 'toAddGoodsCategoryPackage', '&nbsp;', '/goodsCategory/addGoodsCategory.json', '102', '7');
INSERT INTO `RIGHT_OPERATE` VALUES ('120', '删除房型', 'admin', '2013-11-12 16:03:50', 'delHotelRoomAction', '0', 'delHotelRoomAction', 'delHotelRoomAction', ' ', '178', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('121', '编辑套餐', 'admin', '2013-11-12 16:04:03', 'toEditPackage', '0', 'toEditPackage', '&nbsp;', '/goodsCommon/updatePackage.json', '102', '2');
INSERT INTO `RIGHT_OPERATE` VALUES ('122', '添加套餐', 'admin', '2013-11-12 16:04:48', 'toAddPackage', '1', 'toAddPackage', '&nbsp;', '/goodsCommon/savePackage.json', '102', '3');
INSERT INTO `RIGHT_OPERATE` VALUES ('123', '编辑房型', 'admin', '2013-11-12 16:09:58', 'editHotelRoomAction', '0', 'editHotelRoomAction', 'editHotelRoomAction', ' ', '178', '2');
INSERT INTO `RIGHT_OPERATE` VALUES ('124', '添加房型', 'admin', '2013-11-12 16:11:37', 'addHotelRoomAction', '1', 'addHotelRoomAction', 'addHotelRoomAction', null, '178', '3');
INSERT INTO `RIGHT_OPERATE` VALUES ('125', '删除分类', 'admin', '2013-11-12 16:25:39', 'delGoodsCategoryHotel', '0', 'delGoodsCategoryHotel', 'delGoodsCategoryHotel', null, '182', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('126', '编辑分类', 'admin', '2013-11-12 16:27:26', 'editGoodsCategoryHotel', '0', 'editGoodsCategoryHotel', 'editGoodsCategoryHotel', null, '182', '2');
INSERT INTO `RIGHT_OPERATE` VALUES ('127', '添加分类', 'admin', '2013-11-12 16:27:51', 'toAddGoodsCategoryHotel', '1', 'toAddGoodsCategoryHotel', 'toAddGoodsCategoryHotel', null, '182', '3');
INSERT INTO `RIGHT_OPERATE` VALUES ('129', '删除分类', 'admin', '2013-11-12 17:34:27', 'delGoodsCategoryTheater', '0', 'delGoodsCategoryTheater', 'delGoodsCategoryTheater', null, '189', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('130', '编辑分类', 'admin', '2013-11-12 17:35:01', 'editGoodsCategoryTheater', '0', 'editGoodsCategoryTheater', 'editGoodsCategoryTheater', null, '189', '2');
INSERT INTO `RIGHT_OPERATE` VALUES ('131', '添加分类', 'admin', '2013-11-12 17:35:31', 'toAddGoodsCategoryTheater', '1', 'toAddGoodsCategoryTheater', 'toAddGoodsCategoryTheater', null, '189', '3');
INSERT INTO `RIGHT_OPERATE` VALUES ('132', '删除分类', 'admin', '2013-11-12 17:54:47', 'delGoodsCategoryGoodCom', '0', 'delGoodsCategoryGoodCom', 'delGoodsCategoryGoodCom', null, '43', '1');
INSERT INTO `RIGHT_OPERATE` VALUES ('133', '编辑分类', 'admin', '2013-11-12 17:57:49', 'editGoodsCategoryGoodCom', '0', 'editGoodsCategoryGoodCom', 'editGoodsCategoryGoodCom', null, '43', '2');
INSERT INTO `RIGHT_OPERATE` VALUES ('134', '添加分类', 'admin', '2013-11-12 17:58:18', 'toAddGoodsCategoryGoodCom', '1', 'toAddGoodsCategoryGoodCom', 'toAddGoodsCategoryGoodCom', null, '43', '3');
INSERT INTO `RIGHT_OPERATE` VALUES ('156', '新增数据字典', 'admin', '2013-11-14 16:18:45', 'addSystemCode', '1', 'addSystemCode', '新增数据字典', 'operation/system/savaSystemCode.json', '204', '4');
INSERT INTO `RIGHT_OPERATE` VALUES ('157', '编辑数据字典', 'admin', '2013-11-14 17:03:17', 'editSystemCode', '0', 'editSystemCode', '编辑数据字典', 'operation/system/updateSystemCode.json', '204', '5');
INSERT INTO `RIGHT_OPERATE` VALUES ('158', '新增模板', 'admin', '2013-11-14 17:07:17', 'addMould', '1', 'addMould', '新增模板', 'operation/system/savaMould.json', '205', '4');
INSERT INTO `RIGHT_OPERATE` VALUES ('159', '编辑模板', 'admin', '2013-11-14 17:08:21', 'editMould', '0', 'editMould', '编辑模板', 'operation/system/updateMould.json', '205', '5');
INSERT INTO `RIGHT_OPERATE` VALUES ('160', '编辑模板', 'admin', '2013-11-22 16:51:58', 'editMould', '0', 'editMould', '编辑模板', 'operation/system/updateMould.json', '224', '5');
INSERT INTO `RIGHT_OPERATE` VALUES ('161', '新增模板', 'admin', '2013-11-22 16:53:10', 'addMould', '1', 'addMould', '新增模板', 'operation/system/savaMould.json', '224', '4');
INSERT INTO `RIGHT_OPERATE` VALUES ('162', '编辑数据字典', 'admin', '2013-11-22 16:54:56', 'editSystemCode', '0', 'editSystemCode', '<font face=\"helvetica, arial, verdana, sans-serif\" size=\"2\">编辑数据字典</font>', 'operation/system/updateSystemCode.json', '223', '5');
INSERT INTO `RIGHT_OPERATE` VALUES ('163', '新增数据字典', 'admin', '2013-11-22 16:55:48', 'addSystemCode', '1', 'addSystemCode', '<font face=\"helvetica, arial, verdana, sans-serif\" size=\"2\">新增数据字典</font>', 'operation/system/savaSystemCode.json', '223', '4');

insert into RIGHT_OPERATE (OP_ID, OP_NAME, CREATE_USER, CREATE_DATE, OP_ACTION, OP_IS_BTN, OP_BTN_ID, OP_DESC, OP_URL, OP_MENUID, OP_SORT) values('164','提交','admin','2013-11-27 14:59:32','cancelVoucher','1','','<font face=\"helvetica, arial, verdana, sans-serif\" size=\"2\">散客订单 退订 提交</font>','voucher/cancelVoucher.json,voucher/cancelVoucherList.json,operation/system/getSystemCodeByType.json','193','1');
insert into RIGHT_OPERATE (OP_ID, OP_NAME, CREATE_USER, CREATE_DATE, OP_ACTION, OP_IS_BTN, OP_BTN_ID, OP_DESC, OP_URL, OP_MENUID, OP_SORT) values('165','审核','admin','2013-11-27 15:06:40','cancelVoucherByConfirm','1','','散客,退订 审核','voucher/cancelVoucherByConfirm.json,voucher/cancelVoucherList.json,operation/system/getSystemCodeByType.json','193','2');
insert into RIGHT_OPERATE (OP_ID, OP_NAME, CREATE_USER, CREATE_DATE, OP_ACTION, OP_IS_BTN, OP_BTN_ID, OP_DESC, OP_URL, OP_MENUID, OP_SORT) values('166','审核不通过','admin','2013-11-27 15:07:25','cancelVoucherByNoConfirm','1','','散客,退订,审核不通过','voucher/cancelVoucherByNoConfirm.json,voucher/cancelVoucherList.json,operation/system/getSystemCodeByType.json','193','3');
insert into RIGHT_OPERATE (OP_ID, OP_NAME, CREATE_USER, CREATE_DATE, OP_ACTION, OP_IS_BTN, OP_BTN_ID, OP_DESC, OP_URL, OP_MENUID, OP_SORT) values('167','提交','admin','2013-11-27 15:35:07','cancelVoucher','1','','团体,退订,提交','voucher/cancelVoucher.json,voucher/cancelVoucherList.json,operation/system/getSystemCodeByType.json','190','1');
insert into RIGHT_OPERATE (OP_ID, OP_NAME, CREATE_USER, CREATE_DATE, OP_ACTION, OP_IS_BTN, OP_BTN_ID, OP_DESC, OP_URL, OP_MENUID, OP_SORT) values('168','审核','admin','2013-11-27 15:36:34','cancelVoucherByConfirm','1','','团体,退订,审核通过','voucher/cancelVoucherList.json,voucher/cancelVoucherByConfirm.json,operation/system/getSystemCodeByType.json','190','2');
insert into RIGHT_OPERATE (OP_ID, OP_NAME, CREATE_USER, CREATE_DATE, OP_ACTION, OP_IS_BTN, OP_BTN_ID, OP_DESC, OP_URL, OP_MENUID, OP_SORT) values('169','审核不通过','admin','2013-11-27 15:40:16','cancelVoucherByNoConfirm','1','','团体,退订,审核不通过','voucher/cancelVoucherByNoConfirm.json,voucher/cancelVoucherList.json,operation/system/getSystemCodeByType.json','190','3');
insert into RIGHT_OPERATE (OP_ID, OP_NAME, CREATE_USER, CREATE_DATE, OP_ACTION, OP_IS_BTN, OP_BTN_ID, OP_DESC, OP_URL, OP_MENUID, OP_SORT) values('170','提交','admin','2013-11-27 15:41:52','changeSum','1','','团体,修改人数,提交','voucher/changeSum.json,voucher/cancelVoucherList.json,operation/system/getSystemCodeByType.json','190','1');
insert into RIGHT_OPERATE (OP_ID, OP_NAME, CREATE_USER, CREATE_DATE, OP_ACTION, OP_IS_BTN, OP_BTN_ID, OP_DESC, OP_URL, OP_MENUID, OP_SORT) values('171','审核','admin','2013-11-27 15:42:51','changeSumByConfirm','1','','团体,修改人数,审核通过','voucher/changeSumConfirm.json,voucher/cancelVoucherList.json,operation/system/getSystemCodeByType.json','190','2');
insert into RIGHT_OPERATE (OP_ID, OP_NAME, CREATE_USER, CREATE_DATE, OP_ACTION, OP_IS_BTN, OP_BTN_ID, OP_DESC, OP_URL, OP_MENUID, OP_SORT) values('172','审核不通过','admin','2013-11-27 15:43:38','changeSumByNoConfirm','1','','团体,修改人数,审核不通过','voucher/changeSumNoConfirm.json,voucher/cancelVoucherList.json,operation/system/getSystemCodeByType.json','190','3');
insert into RIGHT_OPERATE (OP_ID, OP_NAME, CREATE_USER, CREATE_DATE, OP_ACTION, OP_IS_BTN, OP_BTN_ID, OP_DESC, OP_URL, OP_MENUID, OP_SORT) values('173','提交','admin','2013-11-27 15:45:34','changeDate','1','','团体,改期,提交','voucher/changeDate.json,voucher/cancelVoucherList.json,operation/system/getSystemCodeByType.json','190','1');
insert into RIGHT_OPERATE (OP_ID, OP_NAME, CREATE_USER, CREATE_DATE, OP_ACTION, OP_IS_BTN, OP_BTN_ID, OP_DESC, OP_URL, OP_MENUID, OP_SORT) values('174','审核','admin','2013-11-27 15:51:00','changeDateByConfirm','1','','团体,改期,审核通过','voucher/changeDateConfirm.json,voucher/cancelVoucherList.json,operation/system/getSystemCodeByType.json','190','2');
insert into RIGHT_OPERATE (OP_ID, OP_NAME, CREATE_USER, CREATE_DATE, OP_ACTION, OP_IS_BTN, OP_BTN_ID, OP_DESC, OP_URL, OP_MENUID, OP_SORT) values('175','审核不通过','admin','2013-11-27 15:56:44','changeDateByNoConfirm','1','','团体订单,改期,审核不通过','voucher/changeDateNoConfirm.json,voucher/cancelVoucherList.json,operation/system/getSystemCodeByType.json','190','3');



INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1306', '120', '21');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1307', '120', '2');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1308', '120', '4');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1309', '120', '5');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1310', '120', '6');

INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1313', '120', '24');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1314', '120', '25');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1315', '120', '3');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1316', '120', '26');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1334', '125', '21');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1335', '125', '2');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1336', '125', '4');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1337', '125', '5');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1338', '125', '6');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1340', '125', '24');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1341', '125', '24');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1342', '125', '25');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1343', '125', '3');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1344', '125', '26');



INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1755', '120', '4');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1756', '120', '5');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1757', '120', '6');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1759', '120', '7');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1760', '120', '8');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1761', '120', '9');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1762', '120', '1');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1763', '120', '2');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1764', '120', '3');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1765', '120', '13');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1766', '120', '14');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1767', '120', '15');

INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1771', '120', '10');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1772', '120', '11');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1773', '120', '12');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1774', '120', '20');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1775', '120', '21');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1776', '120', '22');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1799', '125', '4');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1800', '125', '5');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1801', '125', '6');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1803', '125', '7');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1804', '125', '8');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1805', '125', '9');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1806', '125', '1');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1807', '125', '2');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1808', '125', '3');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1809', '125', '13');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1810', '125', '14');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1811', '125', '15');

INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1815', '125', '10');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1816', '125', '11');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1817', '125', '12');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1818', '125', '20');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1819', '125', '21');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1820', '125', '22');



INSERT INTO `SYS_DICT` VALUES ('FRAMEWORK_DESKTOPICON', 'crm-gly', '管理员', '10', '');
INSERT INTO `SYS_DICT` VALUES ('FRAMEWORK_GROUPTYPE', '1', '运营商', '1', '');
INSERT INTO `SYS_DICT` VALUES ('FRAMEWORK_GROUPTYPE', '2', '事业部', '2', '');
INSERT INTO `SYS_DICT` VALUES ('FRAMEWORK_GROUPTYPE', '3', '景区', '3', '');
INSERT INTO `SYS_DICT` VALUES ('FRAMEWORK_GROUPTYPE', '6', '渠道商', '6', '');
INSERT INTO `SYS_DICT` VALUES ('FRAMEWORK_STARTICON', 'a', '开始图标A', '10', '');
INSERT INTO `SYS_DICT` VALUES ('FRAMEWORK_DESKTOPICON', 'crm-yonghu', '用户', '20', '');
INSERT INTO `SYS_DICT` VALUES ('FRAMEWORK_DESKTOPICON', 'crm-baobiao', '报表', '30', '');
INSERT INTO `SYS_DICT` VALUES ('FRAMEWORK_DESKTOPICON', 'crm-caidan', '菜单', '30', '');
INSERT INTO `SYS_DICT` VALUES ('FRAMEWORK_DESKTOPICON', 'crm-caozuo', '操作', '40', '');
INSERT INTO `SYS_DICT` VALUES ('FRAMEWORK_DESKTOPICON', 'crm-fenzu', '分组', '50', '');
INSERT INTO `SYS_DICT` VALUES ('FRAMEWORK_DESKTOPICON', 'crm-juese', '角色', '60', '');
INSERT INTO `SYS_DICT` VALUES ('FRAMEWORK_DESKTOPICON', 'crm-xtpz', '系统配置', '70', '');
INSERT INTO `SYS_DICT` VALUES ('FRAMEWORK_DESKTOPICON', 'crm-yewu', '业务', '80', '');
INSERT INTO `SYS_DICT` VALUES ('FRAMEWORK_DESKTOPICON', 'crm-yingxiao', '营销', '90', '');
INSERT INTO `SYS_DICT` VALUES ('FRAMEWORK_MENUSTATE', '1', '启用', '10', '');
INSERT INTO `SYS_DICT` VALUES ('FRAMEWORK_MENUSTATE', '0', '禁用', '1', '');
INSERT INTO `SYS_DICT` VALUES ('FRAMEWORK_MENUISSHOW', '1', '显示', '10', '');
INSERT INTO `SYS_DICT` VALUES ('FRAMEWORK_MENUISSHOW', '0', '隐藏', '10', '');

INSERT INTO `SYS_DICT` VALUES ('COMPANY_TYPE', '1', '国有企业', '1', '公司类型');
INSERT INTO `SYS_DICT` VALUES ('COMPANY_TYPE', '2', '外资企业', '2', '公司类型');
INSERT INTO `SYS_DICT` VALUES ('COMPANY_TYPE', '3', '私有企业', '3', '公司类型');
INSERT INTO `SYS_DICT` VALUES ('COMPANY_TYPE', '4', '民营企业', '4', '公司类型');
INSERT INTO `SYS_DICT` VALUES ('COMPANY_TYPE', '5', '合资企业', '5', '公司类型');
INSERT INTO `SYS_DICT` VALUES ('COMPANY_TYPE', '6', '个体户', '6', '公司类型');
INSERT INTO `SYS_DICT` VALUES ('QUALIFICATION_LEVEL', '1', '卓越', '1', '资质类型');
INSERT INTO `SYS_DICT` VALUES ('QUALIFICATION_LEVEL', '2', '优秀', '2', '资质类型');
INSERT INTO `SYS_DICT` VALUES ('QUALIFICATION_LEVEL', '3', '合格', '3', '资质类型');

insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_STARTICON','orderSmall','订单管理','20','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_DESKTOPICON','orderBig','订单管理','100','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_STARTICON','channelSmall','渠道商管理','30','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_DESKTOPICON','channelBig','渠道商管理','110','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_STARTICON','operationSmall','运营商管理','40','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_DESKTOPICON','operationBig','运营商管理','120','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_STARTICON','actionSmall','操作管理','50','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_DESKTOPICON','actionBig','操作管理','130','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_STARTICON','userSmall','用户管理','60','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_DESKTOPICON','userBig','用户管理','140','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_STARTICON','goodsSmall','通用商品管理','70','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_DESKTOPICON','goodsBig','通用商品管理','150','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_STARTICON','organizationSmall','机构管理','80','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_DESKTOPICON','organizationBig','机构管理','160','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_STARTICON','ticketSmall','景区门票管理','90','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_DESKTOPICON','ticketBig','景区门票管理','170','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_STARTICON','goodsTypeSmall','商品类型管理','100','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_DESKTOPICON','goodsTypeBig','商品类型管理','180','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_STARTICON','theaterSmall','剧院管理','110','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_DESKTOPICON','theaterBig','剧院管理','190','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_STARTICON','guideSmall','导游管理','120','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_DESKTOPICON','guideBig','导游管理','200','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_STARTICON','webSmall','网站维护管理','130','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_DESKTOPICON','webBig','网站维护管理','210','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_STARTICON','ruleSmall','规则管理','140','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_DESKTOPICON','ruleBig','规则管理','220','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_STARTICON','divisionSmall','事业部管理','150','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_DESKTOPICON','divisionBig','事业部管理','230','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_STARTICON','supplierSmall','供应商管理','160','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_DESKTOPICON','supplierBig','供应商管理','240','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_STARTICON','merchantSmall','商户管理','170','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_DESKTOPICON','merchantBig','商户管理','250','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_STARTICON','equipmentSmall','设备管理','180','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_DESKTOPICON','equipmentBig','设备管理','260','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_STARTICON','systemSmall','系统管理','190','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_DESKTOPICON','systemBig','系统管理','270','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_STARTICON','commentSmall','评论管理','200','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_DESKTOPICON','commentBig','评论管理','280','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_STARTICON','packagesSmall','套票管理 ','210','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_DESKTOPICON','packagesBig','套票管理 ','290','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_STARTICON','configurationSmall','系统配置','220','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_DESKTOPICON','configurationBig','系统配置','300','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_STARTICON','hotelSmall','酒店管理','230','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_DESKTOPICON','hotelBig','酒店管理','310','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_STARTICON','scenicSmall','景区后台管理','240','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_DESKTOPICON','scenicBig','景区后台管理','320','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_STARTICON','scheduleSmall','商品日程管理','250','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_DESKTOPICON','scheduleBig','商品日程管理','330','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_STARTICON','golfSmall','高尔夫管理 ','260','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_DESKTOPICON','golfBig','高尔夫管理 ','340','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_STARTICON','groupSmall','分组管理','270','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_DESKTOPICON','groupBig','分组管理','350','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_STARTICON','reportSmall','报表中心管理','280','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_DESKTOPICON','reportBig','报表中心管理','360','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_STARTICON','menuSmall','菜单管理','290','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_DESKTOPICON','menuBig','菜单管理','370','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_STARTICON','roleSmall','角色管理','300','');
insert into `SYS_DICT` (`CODE_TYPE`, `CODE_ID`, `CODE_NAME`, `SORT`, `REMARK`) values('FRAMEWORK_DESKTOPICON','roleBig','角色管理','380','');



INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('513', '100', '42');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('514', '100', '43');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('515', '100', '44');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('516', '100', '73');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('517', '100', '74');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('518', '100', '75');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('519', '100', '79');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('520', '100', '80');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('521', '100', '81');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('522', '100', '82');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('523', '100', '38');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('524', '100', '41');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('525', '100', '45');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('526', '100', '46');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('527', '100', '47');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('528', '100', '48');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('529', '100', '39');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('530', '100', '49');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('531', '100', '4');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('532', '100', '5');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('533', '100', '6');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('534', '100', '11');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('535', '100', '20');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('536', '100', '7');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('537', '100', '8');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('538', '100', '9');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('539', '100', '1');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('540', '100', '2');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('541', '100', '3');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('542', '100', '13');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('543', '100', '14');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('544', '100', '15');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('545', '100', '71');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('546', '100', '72');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('547', '1', '23');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('548', '100', '23');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('549', '125', '23');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('550', '120', '23');

INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1489', '1', '7');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1490', '1', '44');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1491', '1', '56');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1492', '1', '61');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1493', '1', '64');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1494', '1', '69');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1495', '1', '72');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1496', '1', '73');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1497', '1', '75');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1498', '1', '78');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1499', '1', '79');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1500', '1', '203');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1501', '1', '204');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1502', '1', '205');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1503', '1', '89');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1504', '1', '225');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1505', '1', '226');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1506', '1', '212');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1507', '1', '21');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1508', '1', '4');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1509', '1', '6');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1510', '1', '62');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1511', '1', '110');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1512', '1', '111');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1513', '1', '112');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1514', '1', '116');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1515', '1', '117');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1516', '1', '118');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1517', '1', '120');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1518', '1', '121');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1519', '1', '122');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1520', '1', '123');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1521', '1', '124');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1522', '1', '126');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1523', '1', '127');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1524', '1', '128');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1525', '1', '129');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1526', '1', '93');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1527', '3', '9');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1528', '3', '43');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1529', '3', '49');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1530', '3', '63');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1531', '3', '137');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1532', '3', '138');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1533', '3', '139');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1534', '3', '140');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1535', '3', '141');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1536', '3', '142');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1537', '3', '207');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1538', '3', '208');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1539', '3', '65');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1540', '3', '113');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1541', '3', '114');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1542', '3', '115');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1543', '3', '190');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1544', '3', '193');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1545', '3', '68');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1546', '3', '143');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1547', '3', '144');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1548', '3', '145');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1549', '3', '146');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1550', '3', '80');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1551', '3', '95');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1552', '3', '165');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1553', '3', '166');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1554', '3', '174');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1555', '3', '178');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1556', '3', '181');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1557', '3', '182');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1558', '3', '96');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1559', '3', '100');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1560', '3', '102');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1561', '3', '133');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1562', '3', '148');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1563', '3', '149');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1564', '3', '154');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1565', '3', '155');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1566', '3', '156');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1567', '3', '157');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1568', '3', '183');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1569', '3', '184');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1570', '3', '185');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1571', '3', '186');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1572', '3', '187');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1573', '3', '188');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1574', '3', '189');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1575', '3', '221');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1576', '3', '222');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1577', '3', '223');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1578', '3', '224');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1579', '3', '21');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1580', '3', '4');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1581', '3', '6');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1582', '3', '25');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1583', '3', '3');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1584', '3', '26');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1585', '3', '62');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1586', '3', '110');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1587', '3', '111');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1588', '3', '112');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1589', '3', '116');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1590', '3', '117');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1591', '3', '118');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1592', '3', '120');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1593', '3', '121');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1594', '3', '122');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1595', '3', '123');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1596', '3', '124');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1597', '3', '126');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1598', '3', '127');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1599', '2', '21');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1600', '2', '4');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1601', '2', '6');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1602', '2', '62');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1603', '2', '110');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1604', '2', '111');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1605', '2', '112');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1606', '2', '116');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1607', '2', '117');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1608', '2', '118');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1609', '2', '120');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1610', '2', '121');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1611', '2', '122');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1612', '2', '123');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1613', '2', '124');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1614', '2', '126');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1615', '2', '127');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1616', '2', '8');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1617', '2', '83');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1618', '2', '86');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1632', '6', '10');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1633', '6', '74');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1634', '6', '103');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1635', '6', '105');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1636', '6', '106');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1637', '6', '107');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1638', '6', '167');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1639', '6', '227');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1640', '6', '228');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1641', '6', '180');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1642', '6', '194');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1643', '6', '195');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1644', '6', '196');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1645', '6', '199');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1646', '6', '21');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1647', '6', '4');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('1648', '6', '6');


INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1921', '1', '42');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1922', '1', '43');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1923', '1', '44');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1924', '1', '73');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1925', '1', '74');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1926', '1', '75');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1927', '1', '79');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1928', '1', '80');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1929', '1', '81');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1930', '1', '82');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1931', '1', '38');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1932', '1', '41');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1933', '1', '45');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1934', '1', '46');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1935', '1', '47');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1936', '1', '48');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1937', '1', '39');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1938', '1', '49');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1939', '1', '156');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1940', '1', '157');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1941', '1', '158');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1942', '1', '159');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1943', '1', '7');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1944', '1', '8');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1945', '1', '9');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1946', '1', '13');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1947', '1', '14');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1948', '1', '15');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1949', '1', '83');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1950', '1', '71');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1951', '1', '72');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1952', '3', '54');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1953', '3', '55');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1954', '3', '56');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1955', '3', '57');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1956', '3', '132');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1957', '3', '133');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1958', '3', '134');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1959', '3', '92');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1960', '3', '93');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1961', '3', '94');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1962', '3', '95');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1963', '3', '96');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1964', '3', '97');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1965', '3', '98');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1966', '3', '37');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1967', '3', '88');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1968', '3', '89');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1969', '3', '108');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1970', '3', '112');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1971', '3', '90');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1972', '3', '109');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1973', '3', '110');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1974', '3', '111');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1975', '3', '120');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1976', '3', '123');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1977', '3', '124');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1978', '3', '125');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1979', '3', '126');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1980', '3', '127');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1981', '3', '85');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1982', '3', '86');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1983', '3', '87');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1984', '3', '113');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1985', '3', '116');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1986', '3', '117');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1987', '3', '118');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1988', '3', '119');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1989', '3', '121');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1990', '3', '122');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1991', '3', '91');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1992', '3', '100');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1993', '3', '101');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1994', '3', '102');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1995', '3', '103');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1996', '3', '104');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1997', '3', '105');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1998', '3', '106');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('1999', '3', '107');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2000', '3', '76');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2001', '3', '77');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2002', '3', '78');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2003', '3', '51');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2004', '3', '52');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2005', '3', '53');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2006', '3', '129');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2007', '3', '130');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2008', '3', '131');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2009', '3', '162');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2010', '3', '163');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2011', '3', '160');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2012', '3', '161');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2013', '3', '7');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2014', '3', '8');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2015', '3', '9');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2016', '3', '13');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2017', '3', '14');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2018', '3', '15');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2019', '3', '10');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2020', '3', '11');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2021', '3', '12');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2022', '3', '20');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2023', '3', '21');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2024', '3', '22');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2025', '3', '83');

INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2026', '2', '58');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2027', '2', '68');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2028', '2', '60');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2029', '2', '69');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2030', '2', '7');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2031', '2', '8');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2032', '2', '9');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2033', '2', '13');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2034', '2', '14');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2035', '2', '15');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2036', '2', '83');

INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2040', '6', '7');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2041', '6', '8');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2042', '6', '9');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2043', '6', '13');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2044', '6', '14');
INSERT INTO `RIGHT_ROLE_OPERATE` VALUES ('2045', '6', '15');


INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('647', '100', '7');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('648', '100', '44');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('649', '100', '56');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('650', '100', '61');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('651', '100', '64');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('652', '100', '69');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('653', '100', '72');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('654', '100', '73');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('655', '100', '75');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('656', '100', '78');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('657', '100', '79');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('658', '100', '89');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('661', '100', '2');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('662', '100', '3');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('663', '100', '4');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('665', '100', '6');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('666', '100', '62');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('667', '100', '110');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('668', '100', '111');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('669', '100', '112');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('670', '100', '116');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('671', '100', '117');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('672', '100', '118');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('673', '100', '120');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('674', '100', '121');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('675', '100', '122');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('676', '100', '123');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('677', '100', '124');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('678', '100', '126');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('679', '100', '127');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('680', '100', '93');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('681', '100', '21');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('682', '1', '11');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('683', '1', '12');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('684', '1', '13');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('685', '100', '11');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('686', '100', '12');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('687', '100', '13');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('688', '125', '11');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('689', '125', '12');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('690', '125', '13');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('691', '120', '11');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('692', '120', '12');
INSERT INTO `RIGHT_ROLE_MENUITEM` VALUES ('693', '120', '13');

update RIGHT_OPERATE set OP_URL = 'member/save.json,group/getGroupTree.json,member/findRoleByGroupId.json' where OP_ID = 14;
update RIGHT_OPERATE set OP_URL = 'member/update.json,group/getGroupTree.json,member/findRoleByGroupId.json' where OP_ID = 15;
update RIGHT_OPERATE set OP_URL = 'member/delete.json' where OP_ID = 13;

