ALTER TABLE `RIGHT_MENUITEM` MODIFY COLUMN `MENU_URL`  varchar(2000) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '²Ëµ¥url' AFTER `MENU_QUICKMENU`;

ALTER TABLE `RIGHT_MENUITEM`
MODIFY COLUMN `MENU_W_NAME`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `MENU_NAME`,
MODIFY COLUMN `MENU_ACTION`  varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL AFTER `MENU_W_NAME`;


ALTER TABLE `RIGHT_OPERATE`
MODIFY COLUMN `OP_ACTION`  varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL AFTER `CREATE_DATE`,
MODIFY COLUMN `OP_URL`  varchar(2000) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '°´Å¥url' AFTER `OP_DESC`;
