update RIGHT_OPERATE set OP_URL = 'member/save.json,group/getGroupTree.json,member/findRoleByGroupId.json' where OP_ID = 14;
update RIGHT_OPERATE set OP_URL = 'member/update.json,group/getGroupTree.json,member/findRoleByGroupId.json' where OP_ID = 15;
update RIGHT_OPERATE set OP_URL = 'member/delete.json' where OP_ID = 13;

/*登陆日志表*/
DROP TABLE IF EXISTS `COMMON_MEMBER_LOGIN`;
CREATE TABLE `COMMON_MEMBER_LOGIN` (
  `LOG_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '日值ID',
  `LOG_UID` bigint(20) NOT NULL COMMENT '用户ID',
  `LOG_NAME` varchar(20) DEFAULT NULL COMMENT '用户名',
  `LOG_MOBILE` varchar(18) DEFAULT NULL COMMENT '电话',
  `LOG_IP` varchar(64) NOT NULL COMMENT '登陆IP',
  `LOG_DATE` datetime NOT NULL COMMENT '登陆时间',
  `LOG_SITE_ID` int(11) DEFAULT NULL COMMENT '从那个业务系统登陆',
  `LOG_SITE_NAME` varchar(50) DEFAULT NULL,
  `LOG_CLIENT_TYPE` int(11) NOT NULL COMMENT '应用类型 1:web 2:ios 3:android 4:html5 5:wifi',
  PRIMARY KEY (`LOG_ID`)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8
/*!50100 PARTITION BY RANGE (LOG_ID)
(PARTITION part0 VALUES LESS THAN (2000000) ENGINE = InnoDB,
 PARTITION part1 VALUES LESS THAN (4000000) ENGINE = InnoDB,
 PARTITION part2 VALUES LESS THAN (6000000) ENGINE = InnoDB,
 PARTITION part3 VALUES LESS THAN (8000000) ENGINE = InnoDB,
 PARTITION part4 VALUES LESS THAN (10000000) ENGINE = InnoDB,
 PARTITION part5 VALUES LESS THAN (12000000) ENGINE = InnoDB,
 PARTITION part6 VALUES LESS THAN (14000000) ENGINE = InnoDB,
 PARTITION part7 VALUES LESS THAN (16000000) ENGINE = InnoDB,
 PARTITION part8 VALUES LESS THAN (18000000) ENGINE = InnoDB,
 PARTITION part9 VALUES LESS THAN (20000000) ENGINE = InnoDB) */;