CREATE TABLE `SYS_OPERATE_LOG` (
  `OP_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `OP_TYPE` int(11) DEFAULT NULL,
  `OP_UID` bigint(20) DEFAULT NULL,
  `OP_NAME` varchar(20) DEFAULT NULL,
  `OP_DATE` datetime DEFAULT NULL,
  `OP_SITE_ID` int(11) DEFAULT NULL,
  `OP_SITE` varchar(50) DEFAULT NULL,
  `OP_INFO` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`OP_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=39 DEFAULT CHARSET=utf8;