// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AdminProto.proto

package com.mopon.protobuf.entity;

public final class AdminBuf {
  private AdminBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AdminOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string adminID = 1;
    /**
     * <code>required string adminID = 1;</code>
     */
    boolean hasAdminID();
    /**
     * <code>required string adminID = 1;</code>
     */
    java.lang.String getAdminID();
    /**
     * <code>required string adminID = 1;</code>
     */
    com.google.protobuf.ByteString
        getAdminIDBytes();

    // optional string adminName = 2;
    /**
     * <code>optional string adminName = 2;</code>
     */
    boolean hasAdminName();
    /**
     * <code>optional string adminName = 2;</code>
     */
    java.lang.String getAdminName();
    /**
     * <code>optional string adminName = 2;</code>
     */
    com.google.protobuf.ByteString
        getAdminNameBytes();

    // optional string adminPwd = 3;
    /**
     * <code>optional string adminPwd = 3;</code>
     */
    boolean hasAdminPwd();
    /**
     * <code>optional string adminPwd = 3;</code>
     */
    java.lang.String getAdminPwd();
    /**
     * <code>optional string adminPwd = 3;</code>
     */
    com.google.protobuf.ByteString
        getAdminPwdBytes();
  }
  /**
   * Protobuf type {@code com.test.Admin}
   */
  public static final class Admin extends
      com.google.protobuf.GeneratedMessage
      implements AdminOrBuilder {
    // Use Admin.newBuilder() to construct.
    private Admin(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Admin(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Admin defaultInstance;
    public static Admin getDefaultInstance() {
      return defaultInstance;
    }

    public Admin getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Admin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              adminID_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              adminName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              adminPwd_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mopon.protobuf.entity.AdminBuf.internal_static_com_test_Admin_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mopon.protobuf.entity.AdminBuf.internal_static_com_test_Admin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mopon.protobuf.entity.AdminBuf.Admin.class, com.mopon.protobuf.entity.AdminBuf.Admin.Builder.class);
    }

    public static com.google.protobuf.Parser<Admin> PARSER =
        new com.google.protobuf.AbstractParser<Admin>() {
      public Admin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Admin(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Admin> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string adminID = 1;
    public static final int ADMINID_FIELD_NUMBER = 1;
    private java.lang.Object adminID_;
    /**
     * <code>required string adminID = 1;</code>
     */
    public boolean hasAdminID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string adminID = 1;</code>
     */
    public java.lang.String getAdminID() {
      java.lang.Object ref = adminID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          adminID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string adminID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAdminIDBytes() {
      java.lang.Object ref = adminID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        adminID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string adminName = 2;
    public static final int ADMINNAME_FIELD_NUMBER = 2;
    private java.lang.Object adminName_;
    /**
     * <code>optional string adminName = 2;</code>
     */
    public boolean hasAdminName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string adminName = 2;</code>
     */
    public java.lang.String getAdminName() {
      java.lang.Object ref = adminName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          adminName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string adminName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAdminNameBytes() {
      java.lang.Object ref = adminName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        adminName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string adminPwd = 3;
    public static final int ADMINPWD_FIELD_NUMBER = 3;
    private java.lang.Object adminPwd_;
    /**
     * <code>optional string adminPwd = 3;</code>
     */
    public boolean hasAdminPwd() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string adminPwd = 3;</code>
     */
    public java.lang.String getAdminPwd() {
      java.lang.Object ref = adminPwd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          adminPwd_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string adminPwd = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAdminPwdBytes() {
      java.lang.Object ref = adminPwd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        adminPwd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      adminID_ = "";
      adminName_ = "";
      adminPwd_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasAdminID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getAdminIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAdminNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getAdminPwdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getAdminIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAdminNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getAdminPwdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mopon.protobuf.entity.AdminBuf.Admin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mopon.protobuf.entity.AdminBuf.Admin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mopon.protobuf.entity.AdminBuf.Admin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mopon.protobuf.entity.AdminBuf.Admin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mopon.protobuf.entity.AdminBuf.Admin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mopon.protobuf.entity.AdminBuf.Admin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mopon.protobuf.entity.AdminBuf.Admin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mopon.protobuf.entity.AdminBuf.Admin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mopon.protobuf.entity.AdminBuf.Admin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mopon.protobuf.entity.AdminBuf.Admin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mopon.protobuf.entity.AdminBuf.Admin prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.test.Admin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mopon.protobuf.entity.AdminBuf.AdminOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mopon.protobuf.entity.AdminBuf.internal_static_com_test_Admin_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mopon.protobuf.entity.AdminBuf.internal_static_com_test_Admin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mopon.protobuf.entity.AdminBuf.Admin.class, com.mopon.protobuf.entity.AdminBuf.Admin.Builder.class);
      }

      // Construct using com.mopon.protobuf.entity.AdminBuf.Admin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        adminID_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        adminName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        adminPwd_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mopon.protobuf.entity.AdminBuf.internal_static_com_test_Admin_descriptor;
      }

      public com.mopon.protobuf.entity.AdminBuf.Admin getDefaultInstanceForType() {
        return com.mopon.protobuf.entity.AdminBuf.Admin.getDefaultInstance();
      }

      public com.mopon.protobuf.entity.AdminBuf.Admin build() {
        com.mopon.protobuf.entity.AdminBuf.Admin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mopon.protobuf.entity.AdminBuf.Admin buildPartial() {
        com.mopon.protobuf.entity.AdminBuf.Admin result = new com.mopon.protobuf.entity.AdminBuf.Admin(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.adminID_ = adminID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.adminName_ = adminName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.adminPwd_ = adminPwd_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mopon.protobuf.entity.AdminBuf.Admin) {
          return mergeFrom((com.mopon.protobuf.entity.AdminBuf.Admin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mopon.protobuf.entity.AdminBuf.Admin other) {
        if (other == com.mopon.protobuf.entity.AdminBuf.Admin.getDefaultInstance()) return this;
        if (other.hasAdminID()) {
          bitField0_ |= 0x00000001;
          adminID_ = other.adminID_;
          onChanged();
        }
        if (other.hasAdminName()) {
          bitField0_ |= 0x00000002;
          adminName_ = other.adminName_;
          onChanged();
        }
        if (other.hasAdminPwd()) {
          bitField0_ |= 0x00000004;
          adminPwd_ = other.adminPwd_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAdminID()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mopon.protobuf.entity.AdminBuf.Admin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mopon.protobuf.entity.AdminBuf.Admin) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string adminID = 1;
      private java.lang.Object adminID_ = "";
      /**
       * <code>required string adminID = 1;</code>
       */
      public boolean hasAdminID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string adminID = 1;</code>
       */
      public java.lang.String getAdminID() {
        java.lang.Object ref = adminID_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          adminID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string adminID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAdminIDBytes() {
        java.lang.Object ref = adminID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          adminID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string adminID = 1;</code>
       */
      public Builder setAdminID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        adminID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string adminID = 1;</code>
       */
      public Builder clearAdminID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        adminID_ = getDefaultInstance().getAdminID();
        onChanged();
        return this;
      }
      /**
       * <code>required string adminID = 1;</code>
       */
      public Builder setAdminIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        adminID_ = value;
        onChanged();
        return this;
      }

      // optional string adminName = 2;
      private java.lang.Object adminName_ = "";
      /**
       * <code>optional string adminName = 2;</code>
       */
      public boolean hasAdminName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string adminName = 2;</code>
       */
      public java.lang.String getAdminName() {
        java.lang.Object ref = adminName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          adminName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string adminName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAdminNameBytes() {
        java.lang.Object ref = adminName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          adminName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string adminName = 2;</code>
       */
      public Builder setAdminName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        adminName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string adminName = 2;</code>
       */
      public Builder clearAdminName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        adminName_ = getDefaultInstance().getAdminName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string adminName = 2;</code>
       */
      public Builder setAdminNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        adminName_ = value;
        onChanged();
        return this;
      }

      // optional string adminPwd = 3;
      private java.lang.Object adminPwd_ = "";
      /**
       * <code>optional string adminPwd = 3;</code>
       */
      public boolean hasAdminPwd() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string adminPwd = 3;</code>
       */
      public java.lang.String getAdminPwd() {
        java.lang.Object ref = adminPwd_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          adminPwd_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string adminPwd = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAdminPwdBytes() {
        java.lang.Object ref = adminPwd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          adminPwd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string adminPwd = 3;</code>
       */
      public Builder setAdminPwd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        adminPwd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string adminPwd = 3;</code>
       */
      public Builder clearAdminPwd() {
        bitField0_ = (bitField0_ & ~0x00000004);
        adminPwd_ = getDefaultInstance().getAdminPwd();
        onChanged();
        return this;
      }
      /**
       * <code>optional string adminPwd = 3;</code>
       */
      public Builder setAdminPwdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        adminPwd_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.test.Admin)
    }

    static {
      defaultInstance = new Admin(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.test.Admin)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_test_Admin_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_test_Admin_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020AdminProto.proto\022\010com.test\"=\n\005Admin\022\017\n" +
      "\007adminID\030\001 \002(\t\022\021\n\tadminName\030\002 \001(\t\022\020\n\010adm" +
      "inPwd\030\003 \001(\tB%\n\031com.mopon.protobuf.entity" +
      "B\010AdminBuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_test_Admin_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_test_Admin_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_test_Admin_descriptor,
              new java.lang.String[] { "AdminID", "AdminName", "AdminPwd", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
